const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const days=['Пн','Вт','Ср','Чт','Пт','Сб'];
const baseSchedule={
 'ХТ-26':{
  Пн:[['Иностранный язык','Стрельникова Ю.А.','308'],['Физическая культура','Гордеева Е.В.','Стадион'],['История','Талагаева Е.Л.','302'],['Основы безопасности и защиты Родины','Гордеева Е.В.','208']],
  Вт:[['Химия','Алимова И.В.','ХК'],['Химия','Алимова И.В.','ХК'],['Биология','Алимова И.В.','ХК'],['Биология','Алимова И.В.','ХК']],
  Ср:[['Иностранный язык','Дорохин А.П.','201'],['Иностранный язык','Стрельникова Ю.А.','308'],['Физическая культура','Гордеева Е.В.','ФОК'],['Математика','Ерохина Т.С.','206']]
 },
 'ТЭОР-26':{
  Пн:[['Химия','Алимова И.В.','304'],['Математика','Ерохина Т.С.','206'],['Физическая культура','Золотарев П.Н.','Стадион'],['История','Талагаева Е.Л.','302']],
  Вт:[['Литература','Куликовская Т.В.','306'],['Физика','Образумова Г.М.','203'],['Иностранный язык','Стрельникова Ю.А.','308'],['Иностранный язык','Дорохин А.П.','304']],
  Ср:[['Основы безопасности и защиты Родины','Гордеева Е.В.','208'],['Литература','Куликовская Т.В.','306'],['Математика','Ерохина Т.С.','206'],['Биология','Алимова И.В.','304']]
 },
 'ТМ-26':{
  Пн:[['Физика','Образумова Г.М.','208'],['Химия','Алимова И.В.','304'],['География','Матусик А.И.','100'],['—','—','—']],
  Вт:[['История','Талагаева Е.Л.','302'],['История','Талагаева Е.Л.','302'],['Обществознание','Талагаева Е.Л.','302'],['Литература','Куликовская Т.В.','306']],
  Ср:[['Литература','Куликовская Т.В.','306'],['Физическая культура','Золотарев П.Н.','ФОК'],['Основы безопасности и защиты Родины','Гордеева Е.В.','208'],['Русский язык','Куликовская Т.В.','306']]
 },
 'ТО-26':{
  Пн:[['Математика','Ерохина Т.С.','206'],['Литература','Куликовская Т.В.','306'],['Химия','Алимова И.В.','304'],['Математика','Ерохина Т.С.','206']],
  Вт:[['География','Матусик А.И.','100'],['Иностранный язык','Стрельникова Ю.А.','308'],['Иностранный язык','Дорохин А.П.','304'],['Литература','Куликовская Т.В.','306']],
  Ср:[['Информатика','Исайкина Н.А.','207'],['Физика','Образумова Г.М.','304'],['Физическая культура','Золотарев П.Н.','ФОК'],['—','—','—']]
 },
 'Э-26':{
  Пн:[['История','Талагаева Е.Л.','302'],['Обществознание','Матусик А.И.','100'],['Физика','Образумова Г.М.','Л 4/1'],['—','—','—']],
  Вт:[['Физическая культура','Гордеева Е.В.','ФОК'],['Литература','Куликовская Т.В.','306'],['География','Матусик А.И.','100'],['Основы безопасности и защиты Родины','Гордеева Е.В.','208']],
  Ср:[['История','Талагаева Е.Л.','302'],['История','Талагаева Е.Л.','302'],['Химия','Алимова И.В.','304'],['Информатика','Исайкина Н.А.','207']]
 },
 'С-26':{
  Пн:[['История','Матусик А.И.','100'],['Информатика','Исайкина Н.А.','207'],['Литература','Куликовская Т.В.','306'],['Литература','Куликовская Т.В.','306']],
  Вт:[['Физика','Образумова Г.М.','304'],['История','Матусик А.И.','100'],['Основы технологии сварки и сварочное оборудование','Назаров О.Ю.','Л 4'],['Математика','Ерохина Т.С.','206']],
  Ср:[['Физика','Образумова Г.М.','304'],['Иностранный язык','Дорохин А.П.','201'],['Иностранный язык','Стрельникова Ю.А.','308'],['Физика','Образумова Г.М.','304']]
 },
 'ХТ-25':{
  Пн:[['Иностранный язык в профессиональной деятельности','Стрельникова Ю.А.','308'],['Физическая культура','Гордеева Е.В.','Стадион'],['История России','Талагаева Е.Л.','302'],['—','—','—']],
  Вт:[['Математические методы решения прикладных профессиональных задач','Ермолаева У.И.','205'],['Математические методы решения прикладных профессиональных задач','Ермолаева У.И.','205'],['—','—','—'],['—','—','—']],
  Ср:[['Органическая химия','Егорова П.С.','ХК'],['Органическая химия','Егорова П.С.','ХК'],['Математические методы решения прикладных профессиональных задач','Ермолаева У.И.','ХК'],['Математические методы решения прикладных профессиональных задач','Ермолаева У.И.','ХК']]
 },
 'ТЭОР-25':{
  Пн:[['Цифровые и информационные технологии в профессиональной деятельности','Пак Б.Е.','205'],['Физическая культура','Золотарев П.Н.','Стадион'],['Метрология, стандартизация и сертификация','Баталина И.А.','203'],['—','—','—']],
  Вт:[['Иностранный язык в профессиональной деятельности','Стрельникова Ю.А.','308'],['Технологическое оборудование и приспособления','Лисова К.Н.','101'],['Инженерная графика','Капырина И.Н.','Л 3'],['Инженерная графика','Капырина И.Н.','Л 3']],
  Ср:[['Математические методы моделирования производственных процессов','Ермолаева У.И.','ХК'],['Математические методы моделирования производственных процессов','Ермолаева У.И.','ХК'],['МДК.05.01 Выполнение работ по рабочей профессии 18494','Бондарев Д.А.','ХК'],['МДК.05.01 Выполнение работ по рабочей профессии 18494','Бондарев Д.А.','ХК']]
 },
 'ТМ-25':{
  Пн:[['Метрология, стандартизация и сертификация','Баталина И.А.','203'],['Математика в профессиональной деятельности','Ермолаева У.И.','201'],['Техническая механика','Лисова К.Н.','101'],['Математика в профессиональной деятельности','Ермолаева У.И.','201']],
  Вт:[['Физическая культура','Золотарев П.Н.','ФОК'],['Основы предпринимательства и финансовой грамотности','Исайкина Н.А.','207'],['МДК.06.01 Освоение работ профессии 40.078 токарь','Пугачева А.Н.','301'],['—','—','—']],
  Ср:[['Информационные технологии в профессиональной деятельности','Пак Б.Е.','Л 4/1'],['Информационные технологии в профессиональной деятельности','Пак Б.Е.','Л 4/1'],['Инженерная графика','Пугачева А.Н.','301'],['Технология машиностроения','Лисова К.Н.','101']]
 },
 'ТО-25':{
  Пн:[['УП.01.01','Мельников В.Н.','Л 3'],['УП.01.01','Мельников В.Н.','Л 3'],['—','—','—'],['—','—','—']],
  Вт:[['Материаловедение','Баталина И.А.','203'],['МДК.01.01 Устройство автомобилей','Назаров О.Ю.','Л 4'],['Материаловедение','Баталина И.А.','203'],['Электротехника и электроника','Назаров О.Ю.','Л 4']],
  Ср:[['УП.01.01','Мельников В.Н.','Л 3'],['УП.01.01','Мельников В.Н.','Л 3'],['УП.01.01','Мельников В.Н.','Л 3'],['УП.01.01','Мельников В.Н.','Л 3']]
 },
 'Э-25':{
  Пн:[['МДК.01.01 Практический бухгалтерский учет активов организации и источников их формирования','Исайкина Н.А.','207'],['Статистика','Иванова А.А.','201'],['Статистика','Иванова А.А.','201'],['МДК.03.01 Выполнение работ по профессии 4993 агент по закупкам','Шинкарева А.М.','201']],
  Вт:[['Математика','Ерохина Т.С.','206'],['Основы бухгалтерского учета','Исайкина Н.А.','207'],['Основы бухгалтерского учета','Исайкина Н.А.','207'],['Налоги и налогообложение','Иванова А.А.','201']],
  Ср:[['Математика','Ерохина Т.С.','206'],['Основы бухгалтерского учета','Исайкина Н.А.','207'],['Основы бухгалтерского учета','Исайкина Н.А.','207'],['Налоги и налогообложение','Иванова А.А.','201']]
 },
 'С-25':{
  Пн:[['Физическая культура','Золотарев П.Н.','ФОК'],['Математика','Ерохина Т.С.','206'],['Иностранный язык в профессиональной деятельности','Стрельникова Ю.А.','308'],['Основы инженерной графики','Капырина И.Н.','100']],
  Вт:[['Допуски и технические измерения','Назаров О.Ю.','Л 4'],['Физика','Образумова Г.М.','208'],['Математика','Ерохина Т.С.','206'],['Обществознание','Матусик А.И.','100']],
  Ср:[['Физика','Образумова Г.М.','304'],['История','Матусик А.И.','100'],['Иностранный язык','Стрельникова Ю.А.','308'],['Физика','Образумова Г.М.','304']]
 },
 'ХТ-24':{
  Пн:[['Аналитическая химия','Лукина П.В.','ХК'],['Аналитическая химия','Лукина П.В.','ХК'],['Физическая и коллоидная химия','Лукина П.В.','ХК'],['Физическая и коллоидная химия','Лукина П.В.','ХК']],
  Вт:[['Физическая культура','Фильчев А.В.','Стадион'],['Иностранный язык','Стрельникова Ю.А.','308'],['Безопасность жизнедеятельности','Гордеева Е.В.','208'],['Физическая культура','Фильчев А.В.','Стадион']],
  Ср:[['МДК.02.01 Осуществление выбора оборудования','Бондарев Д.А.','ХК'],['МДК.02.01 Осуществление выбора оборудования','Бондарев Д.А.','ХК'],['УП.02.01','Егорова П.С.','ХК'],['УП.02.01','Егорова П.С.','ХК']]
 },
 'ОСАПП-24':{
  Пн:[['МДК.02.01 Управление и обеспечение качества продукции','Тюрикова Е.А.','ХК'],['МДК.02.01 Управление и обеспечение качества продукции','Тюрикова Е.А.','ХК'],['МДК.02.01 Управление и обеспечение качества продукции','Тюрикова Е.А.','ХК'],['МДК.05.01 Выполнение работ по рабочей профессии 14257','Егорова П.С.','ХК']],
  Вт:[['Физическая культура','Фильчев А.В.','ФОК'],['МДК.04.02 Организация работ по устранению недостатков','Пак Б.Е.','206'],['МДК.03.02 Разработка, организация и контроль качества работ','Лисова К.Н.','101'],['МДК.03.02 Разработка, организация и контроль качества работ','Лисова К.Н.','101']],
  Ср:[['МДК.03.02 Разработка, организация и контроль качества работ','Бондарев Д.А.','ХК'],['МДК.04.01 Осуществление текущего мониторинга','Пак Б.Е.','205'],['Иностранный язык в профессиональной деятельности','Стрельникова Ю.А.','308'],['—','—','—']]
 },
 'ТМ-24':{
  Пн:[['Технологическое оборудование и приспособления','Пугачева А.Н.','301'],['Технологическое оборудование и приспособления','Пугачева А.Н.','301'],['Физическая культура','Золотарев П.Н.','ФОК'],['МДК.01.01 Технологические процессы изготовления деталей машин','Пугачева А.Н.','301']],
  Вт:[['МДК.01.01 Технологические процессы изготовления деталей машин','Пугачева А.Н.','301'],['МДК.01.01 Технологические процессы изготовления деталей машин','Пугачева А.Н.','301'],['Процессы формообразования и инструменты','Пугачева А.Н.','301'],['—','—','—']],
  Ср:[['МДК.01.01 Технологические процессы изготовления деталей машин','Пугачева А.Н.','301'],['МДК.01.01 Технологические процессы изготовления деталей машин','Пугачева А.Н.','301'],['МДК.02.01 Управляющие программы для технологического оборудования','Пак Б.Е.','Л 4/1'],['Иностранный язык в профессиональной деятельности','Стрельникова Ю.А.','308']]
 },
 'ТО-24':{
  Пн:[['Основы предпринимательства и финансовой грамотности','Исайкина Н.А.','207'],['МДК.01.01 Устройство автомобилей','Назаров О.Ю.','Л 4'],['МДК.04.02 Освоение профессии сварщик ручной дуговой сварки','Назаров О.Ю.','Л 4'],['МДК.04.02 Освоение профессии сварщик ручной дуговой сварки','Назаров О.Ю.','Л 4']],
  Вт:[['Физическая культура','Фильчев А.В.','ФОК'],['МДК.01.01 Устройство автомобилей','Назаров О.Ю.','Л 4'],['Иностранный язык в профессиональной деятельности','Дорохин А.П.','201'],['Безопасность жизнедеятельности','Гордеева Е.В.','208']],
  Ср:[['География','Матусик А.И.','100'],['Иностранный язык','Стрельникова Ю.А.','308'],['Иностранный язык','Дорохин А.П.','304'],['Литература','Куликовская Т.В.','306']]
 },
 'ТМ-23':{
  Пн:[['Основы бережливого производства','Баталина И.А.','203'],['Основы бережливого производства','Баталина И.А.','203'],['Основы бережливого производства','Баталина И.А.','203'],['МДК.05.01 Планирование, организация и контроль качества деятельности подчиненного персонала','Шинкаева А.М.','203']],
  Вт:[['Иностранный язык в профессиональной деятельности','Шинкарева А.М.','201'],['Метрология, стандартизация и сертификация','Баталина И.А.','203'],['МДК.04.01 Контроль, наладка, подналадка и техническое обслуживание металлорежущего и аддитивного оборудования','Пак Б.Е.','205'],['УП.05.01','Лисова К.Н.','101']],
  Ср:[['МДК.04.01 Контроль, наладка, подналадка и техническое обслуживание металлорежущего и аддитивного оборудования','Пак Б.Е.','206'],['МДК.05.01 Планирование, организация и контроль качества деятельности подчиненного персонала','Шинкаева А.М.','208'],['МДК.04.01 Контроль, наладка, подналадка и техническое обслуживание металлорежущего и аддитивного оборудования','Пак Б.Е.','206'],['—','—','—']]
 },
};
const periods=[
 {number:1,start:'08:30',firstEnd:'09:15',breakStart:'09:15',breakEnd:'09:20',end:'10:00',next:'10:10'},
 {number:2,start:'10:10',firstEnd:'10:55',breakStart:'10:55',breakEnd:'11:00',end:'11:40',next:'12:10'},
 {number:3,start:'12:10',firstEnd:'12:55',breakStart:'12:55',breakEnd:'13:00',end:'13:40',next:'13:50'},
 {number:4,start:'13:50',firstEnd:'14:35',breakStart:'14:35',breakEnd:'14:40',end:'15:20',next:'15:30'},
 {number:5,start:'15:30',firstEnd:'16:15',breakStart:'16:15',breakEnd:'16:20',end:'17:00',next:null}
];
function clockMinutes(value){const [hours,minutes]=value.split(':').map(Number);return hours*60+minutes}
function minutesUntil(time,current){return Math.max(0,Math.ceil(clockMinutes(time)-current))}
const scheduleStorageKey='upk_custom_schedule';
let schedule=JSON.parse(JSON.stringify(baseSchedule));
function cleanLessons(lessons){return Array.isArray(lessons)?lessons.slice(0,5).map(x=>[String(x[0]||''),String(x[1]||''),String(x[2]||'')]):[]}
function loadCustomSchedule(){try{const saved=JSON.parse(localStorage.getItem(scheduleStorageKey)||'null');if(!saved||typeof saved!=='object')return;Object.entries(saved).forEach(([group,groupDays])=>{if(!schedule[group])schedule[group]={};Object.entries(groupDays||{}).forEach(([day,lessons])=>{if(days.includes(day))schedule[group][day]=cleanLessons(lessons)});});}catch(error){console.warn('Не удалось загрузить пользовательское расписание',error)}}
function saveCustomSchedule(){localStorage.setItem(scheduleStorageKey,JSON.stringify(schedule));}
function groupProfile(group){return /^Э[-‑]/i.test(group)?'economy':'technical'}
function refreshGroupOptions(){const select=$('#groupSelect'),editor=$('#editorGroup'),current=select.value,groups=Object.keys(schedule);select.innerHTML=groups.map(group=>`<option value="${escapeHtml(group)}" data-profile="${groupProfile(group)}">${escapeHtml(group)}</option>`).join('');if(editor)editor.innerHTML=groups.map(group=>`<option value="${escapeHtml(group)}">${escapeHtml(group)}</option>`).join('');if(groups.includes(current))select.value=current;applyProfile($('#profileSelect').value)}
function editorRows(){const group=$('#editorGroup').value,day=$('#editorDay').value,lessons=(schedule[group]&&schedule[group][day])||[];$('#editorLessons').innerHTML=Array.from({length:5},(_,i)=>{const x=lessons[i]||['','',''];return `<div class="editor-lesson"><strong>${i+1}</strong><input data-field="subject" value="${escapeHtml(x[0])}" placeholder="Название предмета"><input data-field="teacher" value="${escapeHtml(x[1])}" placeholder="ФИО преподавателя"><input data-field="room" value="${escapeHtml(x[2])}" placeholder="Кабинет"><button class="secondary clear-lesson" type="button" data-index="${i}">Очистить</button></div>`}).join('');$$('.clear-lesson').forEach(button=>button.onclick=()=>{const row=button.parentElement;row.querySelectorAll('input').forEach(input=>input.value='')})}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function initEditor(){const daySelect=$('#editorDay');daySelect.innerHTML=days.map(day=>`<option value="${day}">${day}</option>`).join('');refreshGroupOptions();editorRows()}
function collectEditorRows(){return $$('#editorLessons .editor-lesson').map(row=>[...row.querySelectorAll('input')].map(input=>input.value.trim()))}
function saveEditor(){const group=$('#editorGroup').value,day=$('#editorDay').value;if(!group)return;schedule[group]||(schedule[group]={});schedule[group][day]=collectEditorRows();saveCustomSchedule();refreshGroupOptions();renderSchedule();editorRows();$('#editorStatus').textContent='Изменения сохранены на этом компьютере.'}
function addEditorGroup(){const name=prompt('Введите название новой группы:','Э-27');if(!name||!name.trim())return;const group=name.trim();if(schedule[group]){alert('Такая группа уже существует.');return}schedule[group]={};saveCustomSchedule();refreshGroupOptions();$('#editorGroup').value=group;editorRows();$('#editorStatus').textContent=`Группа ${group} добавлена.`}
function exportScheduleCode(){const code=`const schedule = ${JSON.stringify(schedule,null,2)};`;$('#scheduleCode').value=code;$('#scheduleCodeBox').hidden=false}
function resetCustomSchedule(){if(!confirm('Удалить все локальные изменения расписания?'))return;localStorage.removeItem(scheduleStorageKey);schedule=JSON.parse(JSON.stringify(baseSchedule));refreshGroupOptions();renderSchedule();editorRows();$('#editorStatus').textContent='Восстановлено исходное расписание УПК.'}
const rooms=[
 ['214','Главный корпус','Математика','Иванова Наталья Викторовна','2 этаж'],['305','Главный корпус','Информатика / ИС','Петров Алексей Сергеевич','3 этаж'],['118','Главный корпус','Экономика','Смирнова Елена Викторовна','1 этаж'],['412','Главный корпус','Материаловедение','Фёдоров Кирилл Константинович','4 этаж'],['маст. 1','Мастерские','Станки и инструменты','Егоров Виктор Владимирович','1 корпус'],['маст. 2','Мастерские','Технология металлов','Соколов Андрей Владимирович','1 корпус'],['301','Лабораторный корпус','Программирование','Лебедев Илья Николаевич','3 этаж'],['303','Лабораторный корпус','Базы данных','Никитина Ольга Сергеевна','3 этаж'],['спортзал','Главный корпус','Физическая культура','Волков Игорь Ильич','1 этаж']
];
let selectedDay=Math.min(5,Math.max(0,new Date().getDay()-1)), chart;
function animateMetric(el,value,format){const from=Number(el.dataset.value)||0,to=Number(value)||0,start=performance.now(),duration=600;el.dataset.value=to;function frame(now){const progress=Math.min(1,(now-start)/duration),eased=1-Math.pow(1-progress,4);el.textContent=format(from+(to-from)*eased);if(progress<1)requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function clock(){const d=new Date();$('#clock').textContent=d.toLocaleTimeString('ru-RU');$('#todayDate').textContent=d.toLocaleDateString('ru-RU',{day:'numeric',month:'long'});$('#todayDay').textContent=d.toLocaleDateString('ru-RU',{weekday:'long'});const now=d.getHours()*60+d.getMinutes()+d.getSeconds()/60;const firstStart=clockMinutes(periods[0].start);let status='Занятия завершены на сегодня.';if(d.getDay()!==0){if(now<firstStart){status=`Занятия ещё не начались. До звонка на 1 пару осталось: ${minutesUntil(periods[0].start,now)} мин.`}else if(now<clockMinutes(periods[periods.length-1].end)){for(const period of periods){const start=clockMinutes(period.start),firstEnd=clockMinutes(period.firstEnd),breakEnd=clockMinutes(period.breakEnd),end=clockMinutes(period.end);if(now>=start&&now<firstEnd){status=`Сейчас идёт ${period.number} пара. До пятиминутки осталось: ${minutesUntil(period.breakStart,now)} мин.`;break}if(now>=firstEnd&&now<breakEnd){status=`Сейчас пятиминутка внутри ${period.number} пары. До звонка на 2 часть: ${minutesUntil(period.breakEnd,now)} мин.`;break}if(now>=breakEnd&&now<end){status=`Сейчас идёт ${period.number} пара. До звонка осталось: ${minutesUntil(period.end,now)} мин.`;break}if(period.next&&now>=end&&now<clockMinutes(period.next)){status=`Сейчас перемена. До звонка на ${period.number+1} пару осталось: ${minutesUntil(period.next,now)} мин.`;break}}}}$('#lessonStatus').textContent=status;}
function renderDays(){ $('#dayTabs').innerHTML=days.map((d,i)=>`<button class="${i===selectedDay?'active':''}" data-day="${i}">${d}</button>`).join('');$$('#dayTabs button').forEach(b=>b.onclick=()=>{selectedDay=+b.dataset.day;renderSchedule()})}
function renderSchedule(){renderDays();const g=$('#groupSelect').value,items=(schedule[g]&&schedule[g][days[selectedDay]])||[];$('#scheduleGrid').innerHTML=items.length?items.map((x,i)=>{const p=periods[i%periods.length];return `<article class="schedule-card ${x[0]==='—'?'empty':''}"><span class="lesson-num">${i+1} ПАРА · ${p.start}–${p.end}</span><h3>${x[0]}</h3><p>◉ ${x[1]}</p><p>⌖ Кабинет ${x[2]}</p><small>${p.start}–${p.end} (перерыв ${p.breakStart}–${p.breakEnd})</small></article>`}).join(''):'<div class="card empty-state">Расписание на этот день в присланных листах не указано.</div>';clock();}
function renderRooms(){let q=$('#roomSearch').value.toLowerCase(), b=$('#buildingFilter').value;let found=rooms.filter(r=>(!q||r.join(' ').toLowerCase().includes(q))&&(!b||r[1]===b));$('#roomResults').innerHTML=found.length?found.map(r=>`<article class="room-card"><span class="room-tag">${r[1]}</span><h3>Кабинет ${r[0]}</h3><p><b>${r[2]}</b></p><p>Преподаватель: ${r[3]}</p><p>⌖ ${r[4]}</p></article>`).join(''):'<div class="card">Ничего не найдено. Измените запрос.</div>';}
function n(id){return Math.max(0,Number($(id).value)||0)}
function chartTheme(){const s=getComputedStyle(document.body);return{grid:s.getPropertyValue('--chart-grid').trim(),text:s.getPropertyValue('--chart-text').trim()}}
function syncChartTheme(){if(!chart)return;const c=chartTheme();chart.options.scales.x.ticks.color=c.text;chart.options.scales.y.ticks.color=c.text;chart.options.scales.x.title.color=c.text;chart.options.scales.y.title.color=c.text;chart.options.scales.x.grid.color=c.grid;chart.options.scales.y.grid.color=c.grid;chart.options.plugins.legend.labels.color=c.text;chart.update('none')}
function calcEconomy(){const price=n('#cvpPrice'),variable=n('#cvpVariable'),fixed=n('#cvpFixed'),quantity=n('#cvpQuantity'),margin=price-variable,validMargin=margin>0,bepUnits=validMargin?fixed/margin:0,revenue=price*quantity,profit=margin*quantity-fixed,safety=quantity?((quantity-bepUnits)/quantity*100):0;animateMetric($('#mRevenue'),revenue,money);animateMetric($('#mProfit'),profit,money);animateMetric($('#mBep'),validMargin?Math.ceil(bepUnits):0,v=>validMargin?`${Math.round(v)} шт.`:'—');animateMetric($('#mSafety'),validMargin?safety:0,v=>validMargin?`${v.toFixed(1)}%`:'—');$('#cvpMessage').textContent=validMargin?(profit>=0?`Прибыль: ${money(profit)}`:`Зона убытка: ${money(Math.abs(profit))}`):'Маржинальный доход должен быть больше нуля';$('#cvpMessage').className='hint '+(profit<0||!validMargin?'bad':'');if(window.Chart){const maxQ=Math.max(10,Math.ceil(Math.max(quantity,validMargin?bepUnits:0)*1.35)),tr=[{x:0,y:0},{x:maxQ,y:price*maxQ}],tc=[{x:0,y:fixed},{x:maxQ,y:fixed+variable*maxQ}],bep=validMargin?[{x:bepUnits,y:price*bepUnits}]:[];if(chart){chart.data.datasets[0].data=tr;chart.data.datasets[1].data=tc;chart.data.datasets[2].data=bep;chart.options.scales.x.max=maxQ;chart.update();syncChartTheme();return}const c=chartTheme();chart=new Chart($('#cvpChart'),{type:'line',data:{datasets:[{label:'TR — выручка',data:tr,borderColor:'#2457d6',tension:0},{label:'TC — затраты',data:tc,borderColor:'#e25b69',tension:0},{label:'Точка безубыточности',type:'scatter',data:bep,backgroundColor:'#00a99d',borderColor:'#fff',pointRadius:7,pointBorderWidth:2}]},options:{animation:{duration:600,easing:'easeOutQuart'},responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{color:c.text}}},scales:{x:{type:'linear',min:0,max:maxQ,title:{display:true,text:'Количество, шт.',color:c.text},ticks:{color:c.text},grid:{color:c.grid}},y:{title:{display:true,text:'Рубли',color:c.text},ticks:{color:c.text},grid:{color:c.grid}}}}})}}
function money(v){return Number.isFinite(v)?Math.round(v).toLocaleString('ru-RU')+' ₽':'—'}
function calcTaxes(){const income=n('#napdIncome'),ind=n('#napdIndividuals'),companies=n('#napdCompanies'),emp=n('#napdEmployees'),napd=$('#napdResult');const shareTotal=ind+companies;let napdTax=0;if(emp>0){napd.innerHTML='НПД заблокирован: наличие сотрудников по 422-ФЗ';napd.className='result bad'}else if(income>2400000){napd.innerHTML='НПД заблокирован: лимит 2,4 млн ₽ превышен';napd.className='result bad'}else if(shareTotal<=0){napd.innerHTML='Укажите распределение дохода между физлицами и организациями';napd.className='result bad'}else{napdTax=ind*.04+companies*.06;napd.innerHTML=`Налог: <b>${money(napdTax)}</b> · эффективная ставка ${(napdTax/income*100).toFixed(2)}%`;napd.className='result'}const ui=n('#usnIncome'),ins=n('#usnInsurance'),ue=n('#usnEmployees'),gross=ui*.06,limit=ue>0?gross*.5:gross,deduction=Math.min(ins,limit),usn=Math.max(0,gross-deduction);$('#usnResult').innerHTML=`Налог: <b>${money(usn)}</b><br><small>Вычет ${money(deduction)} (лимит 50% при сотрудниках)</small>`;const u15=n('#usn15Income'),ex=n('#usn15Expenses'),minRate=n('#usn15Min')/100,base=Math.max(0,u15-ex),regular=base*.15,minTax=u15*minRate,usn15=Math.max(regular,minTax);$('#usn15Result').innerHTML=`Налог: <b>${money(usn15)}</b><br><small>${regular<minTax?'Применён минимальный налог':'Доходы минус расходы'}</small>`;$('#taxCompare').innerHTML=`<b>Сравнение:</b> НПД ${money(napdTax||0)} · УСН 6% ${money(usn)} · УСН 15% ${money(usn15)}`;const amount=n('#loanAmount'),rate=n('#loanRate')/1200,term=n('#loanTerm'),pay=rate?amount*rate/(1-Math.pow(1+rate,-term)):amount/Math.max(term,1),leaseCost=n('#leaseCost'),advance=leaseCost*n('#leaseAdvance')/100,leaseBase=leaseCost-advance,leaseTotal=leaseBase*(1+n('#leaseRate')/100),leasePay=leaseTotal/Math.max(n('#leaseTerm'),1);$('#loanResult').innerHTML=`Платёж: <b>${money(pay)}</b>/мес.<br><small>Переплата: ${money(pay*term-amount)}</small>`;$('#leaseResult').innerHTML=`Аванс: <b>${money(advance)}</b><br>Платёж: <b>${money(leasePay)}</b>/мес.<br><small>Итого выплат: ${money(advance+leaseTotal)}</small>`;$('#financeCompare').innerHTML=`<b>Сравнение финансирования:</b> кредит всего ${money(pay*term)} · лизинг всего ${money(advance+leaseTotal)}`}function calcEngineering(){const rho=n('#metal'),l=n('#metalLength')/1000,w=n('#metalWidth')/1000,h=n('#metalHeight')/1000;let v=$('#metalShape').value==='cylinder'?Math.PI*Math.pow(w/2,2)*l:l*w*h;$('#metalResult').textContent=`${(rho*v).toFixed(3)} кг`;const p=n('#volt')*n('#amp')*n('#cos')*(n('#phases')===3?Math.sqrt(3):1)/1000;$('#powerResult').textContent=`${p.toFixed(3)} кВт`}
function summary(){const profile=$('#profileSelect').value,price=n('#cvpPrice'),variable=n('#cvpVariable'),fixed=n('#cvpFixed'),quantity=n('#cvpQuantity'),margin=price-variable,bep=margin>0?fixed/margin:0,revenue=price*quantity,profit=margin*quantity-fixed,safety=quantity&&margin>0?(quantity-bep)/quantity*100:0,common=[['Группа',$('#groupSelect').value]],finance=[['Цена за единицу',money(price)],['Переменные затраты',money(variable)],['Постоянные затраты',money(fixed)],['Плановый объём',quantity+' шт.'],['Выручка',money(revenue)],['Прибыль / убыток',money(profit)],['Точка безубыточности',margin>0?Math.ceil(bep)+' шт.':'—'],['Запас финансовой прочности',margin>0?safety.toFixed(1)+'%':'—'],['Рекомендация по налогам',$('#taxCompare').textContent||'—'],['Нормативная база','422-ФЗ; п. 3.1 ст. 346.21 НК РФ'],['Кредит / лизинг',$('#financeCompare').textContent||'—']],tech=[['Материал',$('#metal').selectedOptions[0].text],['Форма заготовки',$('#metalShape').selectedOptions[0].text],['Длина / ширина / высота',`${$('#metalLength').value} / ${$('#metalWidth').value} / ${$('#metalHeight').value} мм`],['Плотность',`${$('#metal').value} кг/м³`],['Масса',$('#metalResult').textContent],['Напряжение / ток',`${$('#volt').value} В / ${$('#amp').value} А`],['cos φ',$('#cos').value],['Фазы',$('#phases').value],['Потребляемая мощность',$('#powerResult').textContent]];const block=(title,rows)=>`<div class="summary-block"><h2>${title}</h2>${rows.map(r=>`<div class="summary-row"><span>${r[0]}</span><span>${r[1]||'—'}</span></div>`).join('')}</div>`;let html='<div class="print-title"><b>УПК</b><span>'+({economy:'Финансово-экономический паспорт проекта',technical:'Ведомость технологических расчётов',admin:'Сводный отчёт по модулям'}[profile])+'</span><span>'+new Date().toLocaleDateString('ru-RU')+'</span></div>'+block('Общие параметры',common);if(profile==='economy')html+=block('Финансово-экономический паспорт проекта',finance);else if(profile==='technical')html+=block('Ведомость технологических расчётов',tech);else html+=block('Финансово-экономический блок',finance)+block('Технический блок',tech);$('#summaryContent').innerHTML=html+'<p class="muted">Аналитическое резюме: '+(profile==='technical'?'расчётные параметры заготовки и электросети подготовлены для технологического анализа.':'финансовые показатели и режим налогообложения сопоставлены для принятия управленческого решения.')+'</p><div class="signatures">Выполнил студент группы: ____________________<br><br>Проверил преподаватель: ____________________</div>';}
$$('.module-tab').forEach(b=>b.onclick=()=>{$$('.module-tab').forEach(x=>x.classList.remove('active'));$$('.module-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
function allCalc(){calcEconomy();calcTaxes();calcEngineering();summary()}
const storageKey='upkStudentPortal';
function saveState(e){if(e&&e.target.id)try{localStorage.setItem(storageKey+':'+e.target.id,e.target.value)}catch(_){}}
function restoreState(){const profile=localStorage.getItem(storageKey+':profileSelect')||'economy';$('#profileSelect').value=profile;$('#profileSelectMobile').value=profile;$$('input,select').forEach(e=>{const v=localStorage.getItem(storageKey+':'+e.id);if(v!==null&&!['profileSelect','profileSelectMobile'].includes(e.id))e.value=v});applyProfile(profile)}
function applyProfile(profile){$$('.nav-item[data-profile]').forEach(b=>b.hidden=profile!=='admin'&&b.dataset.profile!==profile);const select=$('#groupSelect'),options=[...select.options];options.forEach(o=>o.hidden=profile!=='admin'&&o.dataset.profile!==profile);const available=options.find(o=>!o.hidden);if(select.selectedOptions[0]&&select.selectedOptions[0].hidden&&available)select.value=available.value;renderSchedule();summary();if($('#editorGroup'))editorRows()}
function csvData(){const profile=$('#profileSelect').value,rows=[['Раздел','Показатель','Значение'],['Параметры','Профиль',$('#profileSelect').selectedOptions[0].text],['Параметры','Группа',$('#groupSelect').value]];if(profile!=='technical')rows.push(['Финансы','Выручка',$('#mRevenue').textContent],['Финансы','Прибыль / убыток',$('#mProfit').textContent],['Финансы','Точка безубыточности',$('#mBep').textContent],['Финансы','Запас финансовой прочности',$('#mSafety').textContent],['Финансы','Налоговая рекомендация',$('#taxCompare').textContent],['Финансы','Кредит / лизинг',$('#financeCompare').textContent]);if(profile!=='economy')rows.push(['Технология','Материал',$('#metal').selectedOptions[0].text],['Технология','Плотность',$('#metal').value+' кг/м³'],['Технология','Масса',$('#metalResult').textContent],['Технология','Напряжение / ток',$('#volt').value+' В / '+$('#amp').value+' А'],['Технология','Мощность',$('#powerResult').textContent]);return '﻿'+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\r\n')}
function downloadCsv(){const a=document.createElement('a');a.href='data:text/csv;charset=utf-8,'+encodeURIComponent(csvData());a.download='upk-summary.csv';a.click()}
function copySummary(){const text=$('#summaryContent').innerText;const done=()=>{const b=$('#copyBtn');b.textContent='Скопировано';setTimeout(()=>b.textContent='Копировать для Word',1200)};if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(done).catch(()=>{fallbackCopy(text);done()});else{fallbackCopy(text);done()}}
function fallbackCopy(text){const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}
function openQr(){const url=location.href;$('#qrLink').textContent=url;$('#qrCode').innerHTML='';if(window.QRCode)new QRCode($('#qrCode'),{text:url,width:220,height:220,colorDark:'#111827',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});else $('#qrCode').textContent='QR-библиотека ещё загружается. Повторите открытие окна.';$('#qrModal').hidden=false}
function closeQr(){$('#qrModal').hidden=true}
function importSchedule(){const raw=$('#scheduleImport').value.trim();if(!raw)return;try{const text=raw.replace(/^\s*const\s+(?:schedule|baseSchedule)\s*=\s*/,'').replace(/;\s*$/,'');const imported=JSON.parse(text);if(!imported||typeof imported!=='object')throw new Error('Неверный объект');schedule=JSON.parse(JSON.stringify(baseSchedule));Object.entries(imported).forEach(([group,groupDays])=>{schedule[group]||(schedule[group]={});Object.entries(groupDays||{}).forEach(([day,lessons])=>{if(days.includes(day))schedule[group][day]=cleanLessons(lessons)});});saveCustomSchedule();refreshGroupOptions();renderSchedule();editorRows();$('#editorStatus').textContent='Расписание импортировано и сохранено на этом компьютере.'}catch(error){$('#editorStatus').textContent='Не удалось импортировать: вставьте JSON или корректный экспортированный код.'}}
function registerServiceWorker(){if(!('serviceWorker' in navigator)||location.protocol==='file:')return;navigator.serviceWorker.register('sw.js').catch(()=>{})}
function syncTitleGroup(){const select=$('#titleGroup');if(!select)return;select.innerHTML=[...$('#groupSelect').options].map(o=>`<option value="${escapeHtml(o.value)}">${escapeHtml(o.textContent)}</option>`).join('');select.value=$('#groupSelect').value}
function printTitle(){const type=$('#titleType').value,subject=$('#titleSubject').value||'________________',topic=$('#titleTopic').value||'________________',teacher=$('#titleTeacher').value||'________________',group=$('#titleGroup').value,year=new Date().getFullYear();const win=window.open('','_blank','width=900,height=700');if(!win){alert('Разрешите всплывающие окна для печати титульного листа.');return}win.document.write(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Титульный лист</title><style>@page{size:A4;margin:20mm}body{font-family:"Times New Roman",serif;font-size:14pt;color:#000}.center{text-align:center}.topic{margin-top:55mm;text-align:center;font-size:16pt;font-weight:bold}.details{margin-top:35mm;margin-left:52%;line-height:1.7}.footer{position:fixed;bottom:12mm;left:0;right:0;text-align:center}</style></head><body><div class="center">МИНИСТЕРСТВО ОБРАЗОВАНИЯ ТУЛЬСКОЙ ОБЛАСТИ<br>ГПОУ ТО «УЗЛОВСКИЙ ПОЛИТЕХНИЧЕСКИЙ КОЛЛЕДЖ»</div><div class="topic">${escapeHtml(type)}<br>по дисциплине «${escapeHtml(subject)}»<br>на тему: «${escapeHtml(topic)}»</div><div class="details">Выполнил студент группы ${escapeHtml(group)}<br>____________________________<br><br>Проверил преподаватель<br>${escapeHtml(teacher)}<br>____________________________</div><div class="footer">Узловая<br>${year}</div><script>window.onload=()=>{window.print();window.onafterprint=()=>window.close()}<\/script></body></html>`);win.document.close()}
function calcGrades(){const excellent=Math.max(0,n('#gradeExcellent')),good=Math.max(0,n('#gradeGood')),satisfactory=Math.max(0,n('#gradeSatisfactory')),total=excellent+good+satisfactory,gpa=total?(excellent*5+good*4+satisfactory*3)/total:0,share=total?excellent/total*100:0;let verdict='Введите количество оценок.';if(total&&satisfactory>0)verdict='Обычный диплом (есть удовлетворительные оценки)';else if(total&&share>=75)verdict='Претендует на диплом с отличием (красный диплом) ★';else if(total){const needed=Math.max(0,Math.ceil((.75*total-excellent)/.25));verdict=`Для красного диплома не хватает ${needed} пятёрок`};$('#gradeResult').innerHTML=`Средний балл: <b>${gpa.toFixed(2)}</b><br>Доля пятёрок: <b>${share.toFixed(1)}%</b><br><span>${verdict}</span>`}
function loadDeadlines(){let list=[];try{list=JSON.parse(localStorage.getItem('upk_deadlines')||'[]')}catch(_){list=[]}const today=new Date();today.setHours(0,0,0,0);$('#deadlineList').innerHTML=list.sort((a,b)=>a.date.localeCompare(b.date)).map(item=>{const date=new Date(`${item.date}T00:00:00`),diff=Math.round((date-today)/86400000),label=diff<0?'Срок прошел':diff===0?'Сегодня сдача':`Осталось ${diff} дн.`;return `<div class="deadline-item ${item.done?'done':''}"><div><strong>${escapeHtml(item.title)}</strong><small>${date.toLocaleDateString('ru-RU')}</small></div><span class="deadline-badge ${diff<0?'overdue':''}">${label}</span><div class="deadline-actions"><button class="secondary deadline-toggle" data-id="${item.id}" type="button">${item.done?'Вернуть':'Готово'}</button><button class="secondary deadline-delete" data-id="${item.id}" type="button">Удалить</button></div></div>`}).join('')||'<p class="muted">Дедлайнов пока нет.</p>';$$('.deadline-toggle').forEach(b=>b.onclick=()=>updateDeadline(b.dataset.id));$$('.deadline-delete').forEach(b=>b.onclick=()=>deleteDeadline(b.dataset.id))}
function saveDeadlines(list){localStorage.setItem('upk_deadlines',JSON.stringify(list));loadDeadlines()}
function updateDeadline(id){const list=JSON.parse(localStorage.getItem('upk_deadlines')||'[]');const item=list.find(x=>x.id===id);if(item)item.done=!item.done;saveDeadlines(list)}
function deleteDeadline(id){saveDeadlines(JSON.parse(localStorage.getItem('upk_deadlines')||'[]').filter(x=>x.id!==id))}
function addDeadline(){const title=$('#deadlineTitle').value.trim(),date=$('#deadlineDate').value;if(!title||!date)return;const list=JSON.parse(localStorage.getItem('upk_deadlines')||'[]');list.push({id:Date.now().toString(),title,date,done:false});saveDeadlines(list);$('#deadlineTitle').value='';$('#deadlineDate').value=''}
function closeSidebar(){ $('#sidebar').classList.remove('open');$('#sidebarOverlay').classList.remove('visible'); }
let editorUnlocked=false;
$$('.nav-item').forEach(b=>b.onclick=()=>{if(b.dataset.section==='schedule-editor'&&!editorUnlocked){const expected=localStorage.getItem('upk_editor_pin')||'1234';if(prompt('Введите PIN-код редактора расписания:')!==expected){alert('Неверный PIN-код.');return}editorUnlocked=true}$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.section').forEach(s=>s.classList.toggle('active',s.id===b.dataset.section));closeSidebar();window.scrollTo({top:0,behavior:'smooth'});if(b.dataset.section==='summary')summary()});
$('#groupSelect').onchange=()=>{saveState({target:$('#groupSelect')});syncTitleGroup();renderSchedule();summary()};$$('#profileSelect,#profileSelectMobile').forEach(e=>e.onchange=event=>{$('#profileSelect').value=event.target.value;$('#profileSelectMobile').value=event.target.value;localStorage.setItem(storageKey+':profileSelect',event.target.value);applyProfile(event.target.value)});$('#roomSearch').oninput=e=>{saveState(e);renderRooms()};$('#buildingFilter').onchange=e=>{saveState(e);renderRooms()};$$('input,select').forEach(e=>{e.addEventListener('input',e=>{saveState(e);allCalc()});e.addEventListener('change',e=>{saveState(e);allCalc()})});$('#printBtn').onclick=()=>window.print();$('#csvBtn').onclick=downloadCsv;$('#copyBtn').onclick=copySummary;$('#resetBtn').onclick=()=>{Object.keys(localStorage).filter(k=>k.startsWith(storageKey+':')).forEach(k=>localStorage.removeItem(k));location.reload()};$('#menuBtn').onclick=()=>{$('#sidebar').classList.toggle('open');$('#sidebarOverlay').classList.toggle('visible',$('#sidebar').classList.contains('open'))};$('#sidebarOverlay').onclick=closeSidebar;$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem(storageKey+':theme',document.body.classList.contains('dark')?'dark':'light');syncChartTheme()};$('#qrBtn').onclick=openQr;$('#closeQrBtn').onclick=closeQr;$('#qrModal').onclick=e=>{if(e.target.id==='qrModal')closeQr()};$('#copyLinkBtn').onclick=()=>{const done=()=>{$('#copyLinkBtn').textContent='Ссылка скопирована';setTimeout(()=>$('#copyLinkBtn').textContent='Скопировать ссылку',1500)};if(navigator.clipboard)navigator.clipboard.writeText(location.href).then(done).catch(()=>{fallbackCopy(location.href);done()});else{fallbackCopy(location.href);done()}};$('#editorGroup').onchange=editorRows;$('#editorDay').onchange=editorRows;$('#addGroupBtn').onclick=addEditorGroup;$('#saveScheduleBtn').onclick=saveEditor;$('#exportScheduleBtn').onclick=exportScheduleCode;$('#resetScheduleBtn').onclick=resetCustomSchedule;$('#importScheduleBtn').onclick=importSchedule;$('#changePinBtn').onclick=()=>{const oldPin=localStorage.getItem('upk_editor_pin')||'1234';if(prompt('Текущий PIN-код:')!==oldPin)return;const next=prompt('Новый PIN-код:');if(next&&/^\d{4,}$/.test(next)){localStorage.setItem('upk_editor_pin',next);$('#editorStatus').textContent='PIN-код изменён.'}else alert('PIN должен содержать минимум 4 цифры.')};$('#copyScheduleCodeBtn').onclick=()=>{const copy=navigator.clipboard?.writeText($('#scheduleCode').value);if(copy)copy.then(()=>$('#editorStatus').textContent='Код расписания скопирован в буфер.').catch(()=>{fallbackCopy($('#scheduleCode').value);$('#editorStatus').textContent='Код расписания скопирован в буфер.'});else{fallbackCopy($('#scheduleCode').value);$('#editorStatus').textContent='Код расписания скопирован в буфер.'}};
$('#printTitleBtn').onclick=printTitle;$('#gradeExcellent').oninput=calcGrades;$('#gradeGood').oninput=calcGrades;$('#gradeSatisfactory').oninput=calcGrades;$('#addDeadlineBtn').onclick=addDeadline;loadCustomSchedule();restoreState();initEditor();syncTitleGroup();calcGrades();loadDeadlines();if(localStorage.getItem(storageKey+':theme')==='dark'){$('#themeBtn').click()}clock();setInterval(clock,1000);renderSchedule();renderRooms();allCalc();registerServiceWorker();
