const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const days=['Пн','Вт','Ср','Чт','Пт','Сб'];
const baseSchedule={
 'ХТ-26':{
  Пн:[['Иностранный язык','Стрельникова Ю.А.','308'],['Физическая культура','Гордеева Е.В.','Стадион'],['История','Талагаева Е.Л.','302'],['Основы безопасности и защиты Родины','Гордеева Е.В.','208']],
  Вт:[['Химия','Алимова И.В.','ХК'],['Химия','Алимова И.В.','ХК'],['Биология','Алимова И.В.','ХК'],['Биология','Алимова И.В.','ХК']],
  Ср:[['Иностранный язык','Дорохин А.П.','201'],['Иностранный язык','Стрельникова Ю.А.','308'],['Физическая культура','Гордеева Е.В.','ФОК'],['Математика','Ерохина Т.С.','206']],
  Чт:[['Физика','Образумова Г.М.','Л 4'],['Иностранный язык','Стрельникова Ю.А. / Дорохин А.П.','308 / 100'],['География','Матусик А.И.','100'],['—','—','—']]
 },
 'ТЭОР-26':{
  Пн:[['Химия','Алимова И.В.','304'],['Математика','Ерохина Т.С.','206'],['Физическая культура','Золотарев П.Н.','Стадион'],['История','Талагаева Е.Л.','302']],
  Вт:[['Литература','Куликовская Т.В.','306'],['Физика','Образумова Г.М.','203'],['Иностранный язык','Стрельникова Ю.А.','308'],['Иностранный язык','Дорохин А.П.','304']],
  Ср:[['Основы безопасности и защиты Родины','Гордеева Е.В.','208'],['Литература','Куликовская Т.В.','306'],['Математика','Ерохина Т.С.','206'],['Биология','Алимова И.В.','304']],
  Чт:[['Литература','Куликовская Т.В.','306'],['Физическая культура','Золотарев П.Н.','Стадион'],['Информатика','Исайкина Н.А.','207'],['—','—','—']]
 },
 'ТМ-26':{
  Пн:[['Физика','Образумова Г.М.','208'],['Химия','Алимова И.В.','304'],['География','Матусик А.И.','100'],['—','—','—']],
  Вт:[['История','Талагаева Е.Л.','302'],['История','Талагаева Е.Л.','302'],['Обществознание','Талагаева Е.Л.','302'],['Литература','Куликовская Т.В.','306']],
  Ср:[['Литература','Куликовская Т.В.','306'],['Физическая культура','Золотарев П.Н.','ФОК'],['Основы безопасности и защиты Родины','Гордеева Е.В.','208'],['Русский язык','Куликовская Т.В.','306']],
  Чт:[['Иностранный язык','Стрельникова Ю.А. / Дорохин А.П.','308 / 201'],['Математика','Ерохина Т.С.','206'],['Обществознание','Талагаева Е.Л.','302'],['Биология','Алимова И.В.','304']]
 },
 'ТО-26':{
  Пн:[['Математика','Ерохина Т.С.','206'],['Литература','Куликовская Т.В.','306'],['Химия','Алимова И.В.','304'],['Математика','Ерохина Т.С.','206']],
  Вт:[['География','Матусик А.И.','100'],['Иностранный язык','Стрельникова Ю.А.','308'],['Иностранный язык','Дорохин А.П.','304'],['Литература','Куликовская Т.В.','306']],
  Ср:[['Информатика','Исайкина Н.А.','207'],['Физика','Образумова Г.М.','304'],['Физическая культура','Золотарев П.Н.','ФОК'],['—','—','—']],
  Чт:[['Основы безопасности и защиты Родины','Гордеева Е.В.','208'],['Биология','Алимова И.В.','304'],['Русский язык','Куликовская Т.В.','306'],['Обществознание','Талагаева Е.Л.','302']]
 },
 'Э-26':{
  Пн:[['История','Талагаева Е.Л.','302'],['Обществознание','Матусик А.И.','100'],['Физика','Образумова Г.М.','Л 4/1'],['—','—','—']],
  Вт:[['Физическая культура','Гордеева Е.В.','ФОК'],['Литература','Куликовская Т.В.','306'],['География','Матусик А.И.','100'],['Основы безопасности и защиты Родины','Гордеева Е.В.','208']],
  Ср:[['История','Талагаева Е.Л.','302'],['История','Талагаева Е.Л.','302'],['Химия','Алимова И.В.','304'],['Информатика','Исайкина Н.А.','207']],
  Чт:[['Биология','Алимова И.В.','304'],['Литература','Куликовская Т.В.','306'],['Математика','Ерохина Т.С.','206'],['Математика','Ерохина Т.С.','206']]
 },
 'С-26':{
  Пн:[['История','Матусик А.И.','100'],['Информатика','Исайкина Н.А.','207'],['Литература','Куликовская Т.В.','306'],['Литература','Куликовская Т.В.','306']],
  Вт:[['Физика','Образумова Г.М.','304'],['История','Матусик А.И.','100'],['Основы технологии сварки и сварочное оборудование','Назаров О.Ю.','Л 4'],['Математика','Ерохина Т.С.','206']],
  Ср:[['Физика','Образумова Г.М.','304'],['Иностранный язык','Дорохин А.П.','201'],['Иностранный язык','Стрельникова Ю.А.','308'],['Физика','Образумова Г.М.','304']],
  Чт:[['Математика','Ерохина Т.С.','206'],['Основы безопасности и защиты Родины','Гордеева Е.В.','208'],['Иностранный язык','Стрельникова Ю.А. / Дорохин А.П.','308 / Л 4'],['Русский язык','Куликовская Т.В.','306']]
 },
 'ХТ-25':{
  Пн:[['Иностранный язык в профессиональной деятельности','Стрельникова Ю.А.','308'],['Физическая культура','Гордеева Е.В.','Стадион'],['История России','Талагаева Е.Л.','302'],['—','—','—']],
  Вт:[['Математические методы решения прикладных профессиональных задач','Ермолаева У.И.','205'],['Математические методы решения прикладных профессиональных задач','Ермолаева У.И.','205'],['—','—','—'],['—','—','—']],
  Ср:[['Органическая химия','Егорова П.С.','ХК'],['Органическая химия','Егорова П.С.','ХК'],['Математические методы решения прикладных профессиональных задач','Ермолаева У.И.','ХК'],['Математические методы решения прикладных профессиональных задач','Ермолаева У.И.','ХК']],
  Чт:[['—','—','—'],['Электротехника и электроника','Назаров О.Ю.','Л 4'],['Общая и неорганическая химия','Алимова И.В.','304'],['—','—','—']]
 },
 'ТЭОР-25':{
  Пн:[['Цифровые и информационные технологии в профессиональной деятельности','Пак Б.Е.','205'],['Физическая культура','Золотарев П.Н.','Стадион'],['Метрология, стандартизация и сертификация','Баталина И.А.','203'],['—','—','—']],
  Вт:[['Иностранный язык в профессиональной деятельности','Стрельникова Ю.А.','308'],['Технологическое оборудование и приспособления','Лисова К.Н.','101'],['Инженерная графика','Капырина И.Н.','Л 3'],['Инженерная графика','Капырина И.Н.','Л 3']],
  Ср:[['Математические методы моделирования производственных процессов','Ермолаева У.И.','ХК'],['Математические методы моделирования производственных процессов','Ермолаева У.И.','ХК'],['МДК.05.01 Выполнение работ по рабочей профессии 18494','Бондарев Д.А.','ХК'],['МДК.05.01 Выполнение работ по рабочей профессии 18494','Бондарев Д.А.','ХК']],
  Чт:[['История России','Талагаева Е.Л.','302'],['История России','Талагаева Е.Л.','302'],['Процессы формообразования и инструменты','Пугачева А.Н.','301'],['Охрана труда и бережливое производство','Назаров О.Ю.','Л 4']]
 },
 'ТМ-25':{
  Пн:[['Метрология, стандартизация и сертификация','Баталина И.А.','203'],['Математика в профессиональной деятельности','Ермолаева У.И.','201'],['Техническая механика','Лисова К.Н.','101'],['Математика в профессиональной деятельности','Ермолаева У.И.','201']],
  Вт:[['Физическая культура','Золотарев П.Н.','ФОК'],['Основы предпринимательства и финансовой грамотности','Исайкина Н.А.','207'],['МДК.06.01 Освоение работ профессии 40.078 токарь','Пугачева А.Н.','301'],['—','—','—']],
  Ср:[['Информационные технологии в профессиональной деятельности','Пак Б.Е.','Л 4/1'],['Информационные технологии в профессиональной деятельности','Пак Б.Е.','Л 4/1'],['Инженерная графика','Пугачева А.Н.','301'],['Технология машиностроения','Лисова К.Н.','101']],
  Чт:[['Материаловедение','Баталина И.А.','203'],['Материаловедение','Баталина И.А.','203'],['Техническая механика','Лисова К.Н.','101'],['Основы предпринимательства и финансовой грамотности','Исайкина Н.А.','207']]
 },
 'ТО-25':{
  Пн:[['УП.01.01','Мельников В.Н.','Л 3'],['УП.01.01','Мельников В.Н.','Л 3'],['—','—','—'],['—','—','—']],
  Вт:[['Материаловедение','Баталина И.А.','203'],['МДК.01.01 Устройство автомобилей','Назаров О.Ю.','Л 4'],['Материаловедение','Баталина И.А.','203'],['Электротехника и электроника','Назаров О.Ю.','Л 4']],
  Ср:[['УП.01.01','Мельников В.Н.','Л 3'],['УП.01.01','Мельников В.Н.','Л 3'],['УП.01.01','Мельников В.Н.','Л 3'],['УП.01.01','Мельников В.Н.','Л 3']],
  Чт:[['Информационные технологии в профессиональной деятельности','Пугачева А.Н.','301'],['Техническая механика','Лисова К.Н.','101'],['Современное оборудование, оснастка, инструмент для ТО АТ','Мельников В.Н.','Л 3'],['Современное оборудование, оснастка, инструмент для ТО АТ','Мельников В.Н.','Л 3']]
 },
 'Э-25':{
  Пн:[['МДК.01.01 Практический бухгалтерский учет активов организации и источников их формирования','Исайкина Н.А.','207'],['Статистика','Иванова А.А.','201'],['Статистика','Иванова А.А.','201'],['МДК.03.01 Выполнение работ по профессии 4993 агент по закупкам','Шинкарева А.М.','201']],
  Вт:[['Математика','Ерохина Т.С.','206'],['Основы бухгалтерского учета','Исайкина Н.А.','207'],['Основы бухгалтерского учета','Исайкина Н.А.','207'],['Налоги и налогообложение','Иванова А.А.','201']],
  Ср:[['Математика','Ерохина Т.С.','206'],['Основы бухгалтерского учета','Исайкина Н.А.','207'],['Основы бухгалтерского учета','Исайкина Н.А.','207'],['Налоги и налогообложение','Иванова А.А.','201']],
  Чт:[['МДК.01.01 Практический бухгалтерский учет активов организации','Исайкина Н.А.','207'],['МДК.01.01 Практический бухгалтерский учет активов организации','Исайкина Н.А.','207'],['Статистика','Иванова А.А.','201'],['История России','Матусик А.И.','100']]
 },
 'С-25':{
  Пн:[['Физическая культура','Золотарев П.Н.','ФОК'],['Математика','Ерохина Т.С.','206'],['Иностранный язык в профессиональной деятельности','Стрельникова Ю.А.','308'],['Основы инженерной графики','Капырина И.Н.','100']],
  Вт:[['Допуски и технические измерения','Назаров О.Ю.','Л 4'],['Физика','Образумова Г.М.','208'],['Математика','Ерохина Т.С.','206'],['Обществознание','Матусик А.И.','100']],
  Ср:[['Физика','Образумова Г.М.','304'],['История','Матусик А.И.','100'],['Иностранный язык','Стрельникова Ю.А.','308'],['Физика','Образумова Г.М.','304']],
  Чт:[['УП.02.01 Выполнение сварочных работ','Рябов А.А.','Сварочная'],['УП.02.01 Выполнение сварочных работ','Рябов А.А.','Сварочная'],['УП.02.01 Выполнение сварочных работ','Рябов А.А.','Сварочная'],['УП.02.01 Выполнение сварочных работ','Рябов А.А.','Сварочная']]
 },
 'ХТ-24':{
  Пн:[['Аналитическая химия','Лукина П.В.','ХК'],['Аналитическая химия','Лукина П.В.','ХК'],['Физическая и коллоидная химия','Лукина П.В.','ХК'],['Физическая и коллоидная химия','Лукина П.В.','ХК']],
  Вт:[['Физическая культура','Фильчев А.В.','Стадион'],['Иностранный язык','Стрельникова Ю.А.','308'],['Безопасность жизнедеятельности','Гордеева Е.В.','208'],['Физическая культура','Фильчев А.В.','Стадион']],
  Ср:[['МДК.02.01 Осуществление выбора оборудования','Бондарев Д.А.','ХК'],['МДК.02.01 Осуществление выбора оборудования','Бондарев Д.А.','ХК'],['УП.02.01','Егорова П.С.','ХК'],['УП.02.01','Егорова П.С.','ХК']],
  Чт:[['—','—','—'],['МДК.03.01 Управление персоналом структурного подразделения','Ермолаева У.И.','201'],['Безопасность жизнедеятельности','Гордеева Е.В.','208'],['Иностранный язык в профессиональной деятельности','Стрельникова Ю.А.','308']]
 },
 'ОСАПП-24':{
  Пн:[['МДК.02.01 Управление и обеспечение качества продукции','Тюрикова Е.А.','ХК'],['МДК.02.01 Управление и обеспечение качества продукции','Тюрикова Е.А.','ХК'],['МДК.02.01 Управление и обеспечение качества продукции','Тюрикова Е.А.','ХК'],['МДК.05.01 Выполнение работ по рабочей профессии 14257','Егорова П.С.','ХК']],
  Вт:[['Физическая культура','Фильчев А.В.','ФОК'],['МДК.04.02 Организация работ по устранению недостатков','Пак Б.Е.','206'],['МДК.03.02 Разработка, организация и контроль качества работ','Лисова К.Н.','101'],['МДК.03.02 Разработка, организация и контроль качества работ','Лисова К.Н.','101']],
  Ср:[['МДК.03.02 Разработка, организация и контроль качества работ','Бондарев Д.А.','ХК'],['МДК.04.01 Осуществление текущего мониторинга','Пак Б.Е.','205'],['Иностранный язык в профессиональной деятельности','Стрельникова Ю.А.','308'],['—','—','—']],
  Чт:[['Основы философии','Матусик А.И.','100'],['МДК.04.02 Организация работ по устранению неполадок и отказов','Пак Б.Е.','Л 4/1'],['МДК.03.01 Планирование МТО работ по монтажу и наладке систем','Баталина И.А.','203'],['—','—','—']]
 },
 'ТМ-24':{
  Пн:[['Технологическое оборудование и приспособления','Пугачева А.Н.','301'],['Технологическое оборудование и приспособления','Пугачева А.Н.','301'],['Физическая культура','Золотарев П.Н.','ФОК'],['МДК.01.01 Технологические процессы изготовления деталей машин','Пугачева А.Н.','301']],
  Вт:[['МДК.01.01 Технологические процессы изготовления деталей машин','Пугачева А.Н.','301'],['МДК.01.01 Технологические процессы изготовления деталей машин','Пугачева А.Н.','301'],['Процессы формообразования и инструменты','Пугачева А.Н.','301'],['—','—','—']],
  Ср:[['МДК.01.01 Технологические процессы изготовления деталей машин','Пугачева А.Н.','301'],['МДК.01.01 Технологические процессы изготовления деталей машин','Пугачева А.Н.','301'],['МДК.02.01 Управляющие программы для технологического оборудования','Пак Б.Е.','Л 4/1'],['Иностранный язык в профессиональной деятельности','Стрельникова Ю.А.','308']],
  Чт:[['МДК.02.01 Управляющие программы изготовления деталей для оборудования','Пак Б.Е.','Л 4/1'],['Процессы формообразования и инструменты','Пугачева А.Н.','301'],['Компьютерная графика','Пак Б.Е.','205'],['Процессы формообразования и инструменты','Пугачева А.Н.','301']]
 },
 'ТО-24':{
  Пн:[['Основы предпринимательства и финансовой грамотности','Исайкина Н.А.','207'],['МДК.01.01 Устройство автомобилей','Назаров О.Ю.','Л 4'],['МДК.04.02 Освоение профессии сварщик ручной дуговой сварки','Назаров О.Ю.','Л 4'],['МДК.04.02 Освоение профессии сварщик ручной дуговой сварки','Назаров О.Ю.','Л 4']],
  Вт:[['Физическая культура','Фильчев А.В.','ФОК'],['МДК.01.01 Устройство автомобилей','Назаров О.Ю.','Л 4'],['Иностранный язык в профессиональной деятельности','Дорохин А.П.','201'],['Безопасность жизнедеятельности','Гордеева Е.В.','208']],
  Ср:[['География','Матусик А.И.','100'],['Иностранный язык','Стрельникова Ю.А.','308'],['Иностранный язык','Дорохин А.П.','304'],['Литература','Куликовская Т.В.','306']],
  Чт:[['МДК.03.01 Особенности конструкций автотранспортных средств','Мельников В.Н.','Л 3'],['МДК.03.01 Особенности конструкций автотранспортных средств','Мельников В.Н.','Л 3'],['Физическая культура','Фильчев А.В.','Стадион'],['—','—','—']]
 },
 'ТМ-23':{
  Пн:[['Основы бережливого производства','Баталина И.А.','203'],['Основы бережливого производства','Баталина И.А.','203'],['Основы бережливого производства','Баталина И.А.','203'],['МДК.05.01 Планирование, организация и контроль качества деятельности подчиненного персонала','Шинкаева А.М.','203']],
  Вт:[['Иностранный язык в профессиональной деятельности','Шинкарева А.М.','201'],['Метрология, стандартизация и сертификация','Баталина И.А.','203'],['МДК.04.01 Контроль, наладка, подналадка и техническое обслуживание металлорежущего и аддитивного оборудования','Пак Б.Е.','205'],['УП.05.01','Лисова К.Н.','101']],
  Ср:[['МДК.04.01 Контроль, наладка, подналадка и техническое обслуживание металлорежущего и аддитивного оборудования','Пак Б.Е.','206'],['МДК.05.01 Планирование, организация и контроль качества деятельности подчиненного персонала','Шинкаева А.М.','208'],['МДК.04.01 Контроль, наладка, подналадка и техническое обслуживание металлорежущего и аддитивного оборудования','Пак Б.Е.','206'],['—','—','—']],
  Чт:[['УП.05.01','Лисова К.Н.','101'],['Физическая культура','Фильчев А.В.','Стадион'],['МДК.05.01 Планирование, организация и контроль качества персонала','Шинкарева А.М.','Л 4/1'],['—','—','—']]
 },
};
const periods=[
 {number:1,start:'08:30',firstEnd:'09:15',breakStart:'09:15',breakEnd:'09:20',end:'10:00',next:'10:10'},
 {number:2,start:'10:10',firstEnd:'10:55',breakStart:'10:55',breakEnd:'11:00',end:'11:40',next:'12:10'},
 {number:3,start:'12:10',firstEnd:'12:55',breakStart:'12:55',breakEnd:'13:00',end:'13:40',next:'13:50'},
 {number:4,start:'13:50',firstEnd:'14:35',breakStart:'14:35',breakEnd:'14:40',end:'15:20',next:'15:30'},
 {number:5,start:'15:30',firstEnd:'16:15',breakStart:'16:15',breakEnd:'16:20',end:'17:00',next:null}
];
function clockMinutes(value){const [hours,minutes]=value.split(':').map(Number);return hours*60+minutes}
function minutesUntil(time,current){return Math.max(0,Math.ceil(clockMinutes(time)-current))}
const scheduleStorageKey='upk_custom_schedule_v15';
let schedule=JSON.parse(JSON.stringify(baseSchedule));
function cleanLessons(lessons){return Array.isArray(lessons)?lessons.slice(0,5).map(x=>[String(x[0]||''),String(x[1]||''),String(x[2]||'')]):[]}
function loadCustomSchedule(){try{const saved=JSON.parse(localStorage.getItem(scheduleStorageKey)||'null');if(!saved||typeof saved!=='object')return;Object.entries(saved).forEach(([group,groupDays])=>{if(!schedule[group])schedule[group]={};Object.entries(groupDays||{}).forEach(([day,lessons])=>{if(days.includes(day))schedule[group][day]=cleanLessons(lessons)});});}catch(error){console.warn('Не удалось загрузить пользовательское расписание',error)}}
function saveCustomSchedule(){localStorage.setItem(scheduleStorageKey,JSON.stringify(schedule));}
function groupProfile(group){return /^Э[-‑]/i.test(group)?'economy':'technical'}
function refreshGroupOptions(){const select=$('#groupSelect'),editor=$('#editorGroup'),current=select.value,groups=Object.keys(schedule);select.innerHTML=groups.map(group=>`<option value="${escapeHtml(group)}" data-profile="${groupProfile(group)}">${escapeHtml(group)}</option>`).join('');if(editor)editor.innerHTML=groups.map(group=>`<option value="${escapeHtml(group)}">${escapeHtml(group)}</option>`).join('');if(groups.includes(current))select.value=current;applyProfile($('#profileSelect').value)}
function editorRows(){const group=$('#editorGroup').value,day=$('#editorDay').value,lessons=(schedule[group]&&schedule[group][day])||[];$('#editorLessons').innerHTML=Array.from({length:5},(_,i)=>{const x=lessons[i]||['','',''];return `<div class="editor-lesson"><strong>${i+1}</strong><input data-field="subject" value="${escapeHtml(x[0])}" placeholder="Название предмета"><input data-field="teacher" value="${escapeHtml(x[1])}" placeholder="ФИО преподавателя"><input data-field="room" value="${escapeHtml(x[2])}" placeholder="Кабинет"><button class="secondary clear-lesson" type="button" data-index="${i}">Очистить</button></div>`}).join('');$$('.clear-lesson').forEach(button=>button.onclick=()=>{const row=button.parentElement;row.querySelectorAll('input').forEach(input=>input.value='')})}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
function initEditor(){const daySelect=$('#editorDay');daySelect.innerHTML=days.map(day=>`<option value="${day}">${day}</option>`).join('');refreshGroupOptions();editorRows()}
function collectEditorRows(){return $$('#editorLessons .editor-lesson').map(row=>[...row.querySelectorAll('input')].map(input=>input.value.trim()))}
function saveEditor(){const group=$('#editorGroup').value,day=$('#editorDay').value;if(!group)return;schedule[group]||(schedule[group]={});schedule[group][day]=collectEditorRows();saveCustomSchedule();refreshGroupOptions();renderSchedule();editorRows();$('#editorStatus').textContent='Изменения сохранены на этом компьютере.'}
function addEditorGroup(){const name=prompt('Введите название новой группы:','Э-27');if(!name||!name.trim())return;const group=name.trim();if(schedule[group]){alert('Такая группа уже существует.');return}schedule[group]={};saveCustomSchedule();refreshGroupOptions();$('#editorGroup').value=group;editorRows();$('#editorStatus').textContent=`Группа ${group} добавлена.`}
function exportScheduleCode(){const code=`const schedule = ${JSON.stringify(schedule,null,2)};`;$('#scheduleCode').value=code;$('#scheduleCodeBox').hidden=false}
function resetCustomSchedule(){if(!confirm('Удалить все локальные изменения расписания?'))return;localStorage.removeItem(scheduleStorageKey);schedule=JSON.parse(JSON.stringify(baseSchedule));refreshGroupOptions();renderSchedule();editorRows();$('#editorStatus').textContent='Восстановлено исходное расписание УПК.'}
const rooms=[
 ['100','Главный корпус','Обществознание и география','Матусик А.И.','1 этаж'],
 ['101','Главный корпус','Технологическое оборудование и практика','Лисова К.Н.','1 этаж'],
 ['118','Главный корпус','Экономика организации','Смирнова Е.В.','1 этаж'],
 ['201','Главный корпус','Иностранный язык','Стрельникова Ю.А.','2 этаж'],
 ['203','Главный корпус','Физика, метрология и технология','Образумова Г.М.','2 этаж'],
 ['205','Главный корпус','Инженерная графика и технологии','Ермолаева У.И.','2 этаж'],
 ['206','Главный корпус','Математика и техническая механика','Ерохина Т.С.','2 этаж'],
 ['207','Главный корпус','Информатика','Исайкина Н.А.','2 этаж'],
 ['208','Главный корпус','ОБЗР и безопасность','Гордеева Е.В.','2 этаж'],
 ['214','Главный корпус','Математика','Иванова Н.В.','2 этаж'],
 ['301','Главный корпус','История и обществознание','Талагаева Е.Л.','3 этаж'],
 ['302','Главный корпус','История России','Талагаева Е.Л.','3 этаж'],
 ['304','Главный корпус','Химия и естественные науки','Алимова И.В.','3 этаж'],
 ['305','Главный корпус','Информатика и информационные системы','Петров А.С.','3 этаж'],
 ['306','Главный корпус','Литература','Куликовская Т.В.','3 этаж'],
 ['308','Главный корпус','Иностранный язык','Стрельникова Ю.А.','3 этаж'],
 ['412','Главный корпус','Материаловедение','Фёдоров К.К.','4 этаж'],
 ['ХК','Лабораторный корпус','Химический комплекс','Алимова И.В.','1 этаж'],
 ['Л 3','Лабораторный корпус','Инженерная графика','Капырина И.Н.','1 этаж'],
 ['Л 4','Лабораторный корпус','Технология металлов и сварка','Назаров О.Ю.','1 этаж'],
 ['Л 4/1','Лабораторный корпус','Физика и электротехника','Образумова Г.М.','1 этаж'],
 ['маст. 1','Мастерские','Станки и инструменты','Егоров В.В.','1 корпус'],
 ['маст. 2','Мастерские','Технология металлов и сварка','Соколов А.В.','1 корпус'],
 ['ФОК','Спорткомплекс','Физическая культура','Золотарев П.Н.','1 этаж'],
 ['Стадион','Спорткомплекс','Физическая культура','Гордеева Е.В.','открытая площадка'],
 ['спортзал','Спорткомплекс','Физическая культура','Волков И.И.','1 этаж']
];
let selectedDay=Math.min(5,Math.max(0,new Date().getDay()-1)), chart, lastClockMinute=null, deferredPrompt=null;
function animateMetric(el,value,format){const from=Number(el.dataset.value)||0,to=Number(value)||0,start=performance.now(),duration=600;el.dataset.value=to;function frame(now){const progress=Math.min(1,(now-start)/duration),eased=1-Math.pow(1-progress,4);el.textContent=format(from+(to-from)*eased);if(progress<1)requestAnimationFrame(frame)}requestAnimationFrame(frame)}
function clock(){const d=new Date(),minuteKey=Math.floor(d.getTime()/60000),minuteChanged=lastClockMinute!==null&&lastClockMinute!==minuteKey;lastClockMinute=minuteKey;$('#clock').textContent=d.toLocaleTimeString('ru-RU');$('#todayDate').textContent=d.toLocaleDateString('ru-RU',{day:'numeric',month:'long'});$('#todayDay').textContent=d.toLocaleDateString('ru-RU',{weekday:'long'});if(minuteChanged){renderSchedule();renderRooms();return}const now=d.getHours()*60+d.getMinutes()+d.getSeconds()/60;const firstStart=clockMinutes(periods[0].start);let status='Занятия завершены на сегодня.';if(d.getDay()!==0){if(now<firstStart){status=`Занятия ещё не начались. До звонка на 1 пару осталось: ${minutesUntil(periods[0].start,now)} мин.`}else if(now<clockMinutes(periods[periods.length-1].end)){for(const period of periods){const start=clockMinutes(period.start),firstEnd=clockMinutes(period.firstEnd),breakEnd=clockMinutes(period.breakEnd),end=clockMinutes(period.end);if(now>=start&&now<firstEnd){status=`Сейчас идёт ${period.number} пара. До пятиминутки осталось: ${minutesUntil(period.breakStart,now)} мин.`;break}if(now>=firstEnd&&now<breakEnd){status=`Сейчас пятиминутка внутри ${period.number} пары. До звонка на 2 часть: ${minutesUntil(period.breakEnd,now)} мин.`;break}if(now>=breakEnd&&now<end){status=`Сейчас идёт ${period.number} пара. До звонка осталось: ${minutesUntil(period.end,now)} мин.`;break}if(period.next&&now>=end&&now<clockMinutes(period.next)){status=`Сейчас перемена. До звонка на ${period.number+1} пару осталось: ${minutesUntil(period.next,now)} мин.`;break}}}}$('#lessonStatus').textContent=status;}
function renderDays(){const todayIndex=new Date().getDay()-1;$('#dayTabs').innerHTML=days.map((d,i)=>`<button class="${i===selectedDay?'active':''}" data-day="${i}">${d}${i===todayIndex?' <span class="today-marker" title="Сегодня">●</span>':''}</button>`).join('');$$('#dayTabs button').forEach(b=>b.onclick=()=>{selectedDay=+b.dataset.day;renderSchedule()})}
function selectTomorrow(){const day=new Date().getDay();selectedDay=day>=1&&day<=5?day:0;renderSchedule()}
function updateTomorrowButton(){const btn=$('#tomorrowBtn');if(!btn)return;const day=new Date().getDay(),tomorrowIndex=day>=1&&day<=5?day:0;btn.hidden=selectedDay===tomorrowIndex}
function focusRoom(room){const sectionButton=$('.nav-item[data-section="rooms"]');if(sectionButton){$$('.nav-item').forEach(button=>button.classList.remove('active'));sectionButton.classList.add('active')}$$('.section').forEach(section=>section.classList.toggle('active',section.id==='rooms'));$('#roomSearch').value=room;$('#buildingFilter').value='';renderRooms();window.scrollTo({top:0,behavior:'smooth'})}
function renderSchedule(){renderDays();updateTomorrowButton();const g=$('#groupSelect').value,items=(schedule[g]&&schedule[g][days[selectedDay]])||[],todayIndex=new Date().getDay()-1,now=new Date(),nowMinutes=now.getHours()*60+now.getMinutes()+now.getSeconds()/60;$('#scheduleGrid').innerHTML=items.length?items.map((x,i)=>{const p=periods[i%periods.length],isCurrent=selectedDay===todayIndex&&nowMinutes>=clockMinutes(p.start)&&nowMinutes<clockMinutes(p.end)&&x[0]!=='—',room=escapeHtml(x[2]);return `<article class="schedule-card ${x[0]==='—'?'empty ':''}${isCurrent?'is-current':''}"><span class="lesson-num">${i+1} ПАРА · ${p.start}–${p.end}${isCurrent?' <b class="now-badge">● СЕЙЧАС</b>':''}</span><h3>${escapeHtml(x[0])}</h3><p>◉ ${escapeHtml(x[1])}</p><p>⌖ <button class="room-link" type="button" data-room="${room}">Кабинет ${room}</button></p><small>${p.start}–${p.end} (перерыв ${p.breakStart}–${p.breakEnd})</small></article>`}).join(''):'<div class="card empty-state">Расписание на этот день в присланных листах не указано.</div>';$$('.room-link').forEach(button=>button.onclick=()=>focusRoom(button.dataset.room));clock();}
function normalizeSearch(value){return String(value||'').toLocaleLowerCase('ru-RU').trim().replace(/[^\p{L}\p{N}]+/gu,' ').replace(/\s+/g,' ').trim()}
function searchTokens(value){const normalized=normalizeSearch(value);return normalized?normalized.split(' '):[]}
function getRoomScheduleText(roomNumber){const target=normalizeSearch(roomNumber),values=[];Object.values(schedule).forEach(groupDays=>Object.values(groupDays||{}).forEach(lessons=>(lessons||[]).forEach(lesson=>{if(normalizeSearch(lesson[2])===target)values.push(`${lesson[0]} ${lesson[1]}`)})));return values.join(' ')}
function getRoomLiveStatus(roomNumber){const now=new Date(),dayIndex=now.getDay()-1;if(dayIndex<0||dayIndex>=days.length)return null;const nowMinutes=now.getHours()*60+now.getMinutes()+now.getSeconds()/60;const period=periods.find(item=>nowMinutes>=clockMinutes(item.start)&&nowMinutes<clockMinutes(item.end));if(!period)return{occupied:false};const day=days[dayIndex],target=normalizeSearch(roomNumber);for(const [group,groupDays] of Object.entries(schedule)){const lesson=(groupDays[day]||[])[period.number-1];if(lesson&&normalizeSearch(lesson[2])===target&&lesson[0]&&lesson[0]!=='—')return{occupied:true,lesson:lesson[0],group,teacher:lesson[1],periodNum:period.number}}return{occupied:false}}
function renderRooms(){const query=normalizeSearch($('#roomSearch').value),queryTokens=searchTokens(query),building=$('#buildingFilter').value;const exactCode=query?rooms.filter(room=>normalizeSearch(room[0])===query):[];const found=rooms.filter(room=>{if(building&&room[1]!==building)return false;if(!query)return true;if(exactCode.length)return exactCode.includes(room);const codeTokens=searchTokens(room[0]);if(queryTokens.length===1&&codeTokens.some(token=>token.startsWith(queryTokens[0])))return true;const fields=[room[1],room[2],room[3],room[4],getRoomScheduleText(room[0])];const fieldTokens=fields.flatMap(searchTokens);return queryTokens.every(token=>fieldTokens.some(fieldToken=>fieldToken===token||fieldToken.startsWith(token)))});$('#roomResults').innerHTML=found.length?found.map(room=>{const status=getRoomLiveStatus(room[0]),live=status&&status.occupied;const banner=live?`<div class="room-live-banner occupied"><span class="live-dot pulse">●</span><div><b>Сейчас идёт ${status.periodNum} пара:</b> ${escapeHtml(status.lesson)} · гр. ${escapeHtml(status.group)} (${escapeHtml(status.teacher)})</div></div>`:status?'<div class="room-live-banner free"><span class="live-dot">●</span><div>Сейчас занятий нет</div></div>':'';return `<article class="room-card ${live?'is-occupied':''}"><span class="room-tag">${escapeHtml(room[1])}</span><h3>Кабинет ${escapeHtml(room[0])}</h3><p><b>${escapeHtml(room[2])}</b></p><p>Преподаватель: ${escapeHtml(room[3])}</p><p>⌖ ${escapeHtml(room[4])}</p>${banner}</article>`}).join(''):'<div class="card">Ничего не найдено. Измените запрос.</div>';}
const methodologyData=[
 {id:'bep',category:'economy',categoryLabel:'Экономика и налоги',title:'Точка безубыточности (CVP / BEP)',formula:'BEP = FC / (P − AVC)',variables:'FC — постоянные затраты, ₽; P — цена единицы, ₽; AVC — переменные затраты на единицу, ₽; BEP — критический объем, шт.',derivation:'В точке безубыточности прибыль равна нулю, поэтому выручка равна совокупным затратам: TR = TC. Подставляя TR = P × Q и TC = FC + AVC × Q, получаем P × Q = FC + AVC × Q. После переноса переменной части: Q × (P − AVC) = FC. Отсюда BEP = FC / (P − AVC).',example:'При FC = 85 000 ₽, P = 1 200 ₽ и AVC = 650 ₽: BEP = 85 000 / 550 = 154,5, то есть необходимо реализовать минимум 155 единиц продукции.',keywords:'CVP выручка затраты порог рентабельности точка безубыточности',chart:'bep'},
 {id:'safety',category:'economy',categoryLabel:'Экономика и налоги',title:'Запас финансовой прочности',formula:'FS = ((Q − BEP) / Q) × 100%',variables:'Q — плановый объем продаж, шт.; BEP — точка безубыточности, шт.; FS — запас финансовой прочности, %.',derivation:'Запас прочности показывает, на какую долю может сократиться объем продаж до достижения критической точки. Разность Q − BEP отражает допустимое снижение продаж. Деление на фактический объем Q переводит показатель в относительную форму, а умножение на 100% — в проценты.',example:'При Q = 300 шт. и BEP = 155 шт. FS = ((300 − 155) / 300) × 100% = 48,3%. Это означает, что продажи могут снизиться примерно на 48% до перехода в зону убытка.',keywords:'финансовая прочность риск запас продаж',chart:null},
 {id:'depreciation',category:'economy',categoryLabel:'Экономика и налоги',title:'Линейная амортизация основных средств',formula:'Aгод = (Sперв − Sликв) / T;  Aмес = Aгод / 12',variables:'Sперв — первоначальная стоимость, ₽; Sликв — ликвидационная стоимость, ₽; T — срок полезного использования, лет; A — амортизация.',derivation:'При линейном методе амортизируемая стоимость распределяется равными долями в течение всего срока эксплуатации. Амортизируемая стоимость равна Sперв − Sликв. Деление на T дает годовую сумму, а деление результата на 12 — ежемесячную сумму.',example:'Для оборудования стоимостью 1 200 000 ₽, ликвидационной стоимостью 120 000 ₽ и СПИ 5 лет: Aгод = 216 000 ₽, Aмес = 18 000 ₽. После первого года остаточная стоимость составит 984 000 ₽.',keywords:'амортизация основные средства СПИ остаточная стоимость',chart:'depreciation'},
 {id:'annuity',category:'economy',categoryLabel:'Экономика и налоги',title:'Аннуитетный платёж по кредиту',formula:'A = S × [i(1+i)ⁿ] / [(1+i)ⁿ − 1]',variables:'S — сумма кредита, ₽; i — месячная процентная ставка; n — количество платежей; A — фиксированный ежемесячный платеж.',derivation:'Аннуитет — финансовая рента с равными платежами. Текущая стоимость платежей равна сумме дисконтированных платежей: S = A × [1 − (1+i)⁻ⁿ] / i. Выражая A из равенства, получаем формулу аннуитетного платежа.',example:'Для кредита 500 000 ₽ на 24 месяца под 18% годовых месячная ставка равна 0,015. Ежемесячный платеж составляет примерно 24 962 ₽, а общая сумма выплат — около 599 088 ₽.',keywords:'кредит финансовая рента проценты платеж',chart:'annuity'},
 {id:'usn',category:'economy',categoryLabel:'Экономика и налоги',title:'Налоговый вычет УСН «Доходы» 6%',formula:'Налог к уплате = max(0, Налог начисленный − Вычет)',variables:'Налог начисленный = Доход × 6%; вычет — страховые взносы и иные разрешенные суммы; при наличии сотрудников вычет ограничен 50% начисленного налога.',derivation:'Сначала определяется налоговая база в виде всей выручки, затем применяется ставка 6%. Статья 346.21 НК РФ разрешает уменьшить налог на страховые взносы. Если у организации есть работники, сумма уменьшения не может превышать половину начисленного налога.',example:'При доходе 600 000 ₽ налог равен 36 000 ₽. При взносах 50 000 ₽ и наличии сотрудников максимальный вычет равен 18 000 ₽, поэтому к уплате остается 18 000 ₽.',keywords:'УСН 6% налоговый вычет 346.21 взносы',chart:null},
 {id:'cutting',category:'technology',categoryLabel:'Технология и обработка',title:'Скорость резания при точении',formula:'v = (π × D × n) / 1000',variables:'D — диаметр заготовки, мм; n — частота вращения шпинделя, об/мин; v — скорость резания, м/мин.',derivation:'За один оборот точка на поверхности проходит длину окружности L = πD. За минуту при n оборотах путь равен πDn миллиметров. Перевод из миллиметров в метры выполняется делением на 1000, поэтому v = πDn / 1000.',example:'При D = 80 мм и n = 500 об/мин: v = 3,1416 × 80 × 500 / 1000 = 125,7 м/мин. Для стали это рабочая скорость средней величины.',keywords:'точение резание станок диаметр шпиндель технология',chart:'cutting'},
 {id:'threephase',category:'electrical',categoryLabel:'Электротехника',title:'Электрическая мощность трёхфазной сети',formula:'P = √3 × Uлин × Iлин × cosφ',variables:'Uлин — линейное напряжение, В; Iлин — линейный ток, А; cosφ — коэффициент мощности; P — активная мощность, Вт.',derivation:'Для симметричной трехфазной системы P = 3 × Uф × Iф × cosφ. При соединении звездой Uлин = √3 × Uф, а Iлин = Iф. Подстановка этих соотношений дает P = √3 × Uлин × Iлин × cosφ.',example:'Станок при Uлин = 380 В, Iлин = 12 А и cosφ = 0,82 потребляет P = 1,732 × 380 × 12 × 0,82 ≈ 6,48 кВт.',keywords:'электротехника мощность трехфазная сеть станок cos phi',chart:null},
 {id:'mass',category:'technology',categoryLabel:'Технология и обработка',title:'Плотность и масса заготовок',formula:'m = ρ × V;  Vцилиндра = πr²L',variables:'m — масса, кг; ρ — плотность материала, кг/м³; V — объем, м³; r — радиус, м; L — длина, м.',derivation:'Плотность определяется как отношение массы к объему: ρ = m / V. Умножением обеих частей на V получаем m = ρV. Для цилиндрического прутка объем равен площади основания πr², умноженной на длину L.',example:'Стальной пруток диаметром 50 мм и длиной 2 м имеет объем π × 0,025² × 2 ≈ 0,003927 м³. При плотности стали 7 850 кг/м³ масса составляет примерно 30,8 кг.',keywords:'плотность масса сталь пруток цилиндр объем',chart:null}
];
let methodologyChart=null;
let methodologyCategory='all';
function renderMethodology(){const query=normalizeSearch($('#methodologySearch')?.value||''),tokens=searchTokens(query),grid=$('#methodologyGrid');if(!grid)return;const found=methodologyData.filter(item=>(methodologyCategory==='all'||item.category===methodologyCategory)&&(!tokens.length||tokens.every(token=>searchTokens(`${item.title} ${item.formula} ${item.categoryLabel} ${item.variables} ${item.derivation} ${item.example} ${item.keywords}`).some(value=>value.includes(token)))));grid.innerHTML=found.length?found.map(item=>`<article class="card method-card"><span class="method-category">${escapeHtml(item.categoryLabel)}</span><h2>${escapeHtml(item.title)}</h2><div class="method-card-formula">${escapeHtml(item.formula)}</div><p>${escapeHtml(item.example)}</p><button class="method-details-btn" type="button" data-methodology-id="${item.id}">Подробнее с выводом и графиком →</button></article>`).join(''):'<div class="card empty-state">По вашему запросу формулы не найдены.</div>';$$('[data-methodology-id]').forEach(button=>button.onclick=()=>openMethodologyModal(button.dataset.methodologyId))}
function openMethodologyModal(id){const item=methodologyData.find(value=>value.id===id);if(!item)return;$('#methodologyModalTitle').textContent=item.title;$('#methodologyModalCategory').textContent=item.categoryLabel;$('#methodologyFormula').textContent=item.formula;$('#methodologyVariables').textContent=item.variables;$('#methodologyDerivation').textContent=item.derivation;$('#methodologyExample').textContent=item.example;const chartBox=$('#methodologyChartBox');if(methodologyChart){methodologyChart.destroy();methodologyChart=null}if(item.chart&&window.Chart){chartBox.hidden=false;methodologyChart=createMethodologyChart(item)}else chartBox.hidden=true;$('#methodologyModal').hidden=false;document.body.classList.add('modal-open')}
function createMethodologyChart(item){const c=chartTheme(),canvas=$('#methodologyChart'),common={responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{color:c.text}}},scales:{x:{ticks:{color:c.text},grid:{color:c.grid}},y:{ticks:{color:c.text},grid:{color:c.grid}}}};if(item.chart==='bep'){const tr=[],tc=[];for(let x=0;x<=300;x+=25){tr.push({x,y:1200*x});tc.push({x,y:85000+650*x})}return new Chart(canvas,{type:'line',data:{datasets:[{label:'TR — выручка',data:tr,borderColor:'#2457d6',tension:0},{label:'TC — затраты',data:tc,borderColor:'#e25b69',tension:0}]},options:{...common,scales:{...common.scales,x:{...common.scales.x,type:'linear',title:{display:true,text:'Объем, шт.',color:c.text}},y:{...common.scales.y,title:{display:true,text:'Рубли',color:c.text}}}}})}if(item.chart==='depreciation'){return new Chart(canvas,{type:'line',data:{labels:['0 год','1 год','2 год','3 год','4 год','5 год'],datasets:[{label:'Остаточная стоимость, ₽',data:[1200000,984000,768000,552000,336000,120000],borderColor:'#16845d',backgroundColor:'#16845d33',fill:true}]},options:common})}if(item.chart==='annuity'){return new Chart(canvas,{type:'bar',data:{labels:['1','6','12','18','24'],datasets:[{label:'Основной долг',data:[17462,18412,19834,21800,24962],backgroundColor:'#2457d6'},{label:'Проценты',data:[7500,6550,5128,3162,0],backgroundColor:'#e25b69'}]},options:common})}if(item.chart==='cutting'){const points=[];for(let d=20;d<=160;d+=20)points.push({x:d,y:100000/(Math.PI*d)});return new Chart(canvas,{type:'line',data:{datasets:[{label:'n при v = 100 м/мин',data:points,borderColor:'#00a99d',tension:.25}]},options:{...common,scales:{...common.scales,x:{...common.scales.x,type:'linear',title:{display:true,text:'Диаметр D, мм',color:c.text}},y:{...common.scales.y,title:{display:true,text:'Обороты n, об/мин',color:c.text}}}}})}}
function closeMethodologyModal(){if(methodologyChart){methodologyChart.destroy();methodologyChart=null}$('#methodologyModal').hidden=true;document.body.classList.remove('modal-open')}
function initMethodology(){if(!$('#methodologyGrid'))return;renderMethodology();$('#methodologySearch').oninput=renderMethodology;$$('.method-filter-btn').forEach(button=>button.onclick=()=>{methodologyCategory=button.dataset.category;$$('.method-filter-btn').forEach(item=>item.classList.toggle('active',item===button));renderMethodology()});$('#closeMethodologyBtn').onclick=closeMethodologyModal;$('#methodologyModal').onclick=event=>{if(event.target.id==='methodologyModal')closeMethodologyModal()};document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('#methodologyModal').hidden)closeMethodologyModal()})}
function n(id){return Math.max(0,Number($(id).value)||0)}
function chartTheme(){const s=getComputedStyle(document.body);return{grid:s.getPropertyValue('--chart-grid').trim(),text:s.getPropertyValue('--chart-text').trim()}}
function syncChartTheme(){const c=chartTheme();if(chart){chart.options.scales.x.ticks.color=c.text;chart.options.scales.y.ticks.color=c.text;chart.options.scales.x.title.color=c.text;chart.options.scales.y.title.color=c.text;chart.options.scales.x.grid.color=c.grid;chart.options.scales.y.grid.color=c.grid;chart.options.plugins.legend.labels.color=c.text;chart.update('none')}if(methodologyChart){methodologyChart.options.plugins.legend.labels.color=c.text;Object.values(methodologyChart.options.scales||{}).forEach(axis=>{axis.ticks.color=c.text;axis.grid.color=c.grid;if(axis.title)axis.title.color=c.text});methodologyChart.update('none')}}
function calcEconomy(){const price=n('#cvpPrice'),variable=n('#cvpVariable'),fixed=n('#cvpFixed'),quantity=n('#cvpQuantity'),margin=price-variable,validMargin=margin>0,bepUnits=validMargin?fixed/margin:0,revenue=price*quantity,profit=margin*quantity-fixed,safety=quantity?((quantity-bepUnits)/quantity*100):0;animateMetric($('#mRevenue'),revenue,money);animateMetric($('#mProfit'),profit,money);animateMetric($('#mBep'),validMargin?Math.ceil(bepUnits):0,v=>validMargin?`${Math.round(v)} шт.`:'—');animateMetric($('#mSafety'),validMargin?safety:0,v=>validMargin?`${v.toFixed(1)}%`:'—');$('#cvpMessage').textContent=validMargin?(profit>=0?`Прибыль: ${money(profit)}`:`Зона убытка: ${money(Math.abs(profit))}`):'Маржинальный доход должен быть больше нуля';$('#cvpMessage').className='hint '+(profit<0||!validMargin?'bad':'');if(window.Chart){const maxQ=Math.max(10,Math.ceil(Math.max(quantity,validMargin?bepUnits:0)*1.35)),tr=[{x:0,y:0},{x:maxQ,y:price*maxQ}],tc=[{x:0,y:fixed},{x:maxQ,y:fixed+variable*maxQ}],bep=validMargin?[{x:bepUnits,y:price*bepUnits}]:[];if(chart){chart.data.datasets[0].data=tr;chart.data.datasets[1].data=tc;chart.data.datasets[2].data=bep;chart.options.scales.x.max=maxQ;chart.update();syncChartTheme();return}const c=chartTheme();chart=new Chart($('#cvpChart'),{type:'line',data:{datasets:[{label:'TR — выручка',data:tr,borderColor:'#2457d6',tension:0},{label:'TC — затраты',data:tc,borderColor:'#e25b69',tension:0},{label:'Точка безубыточности',type:'scatter',data:bep,backgroundColor:'#00a99d',borderColor:'#fff',pointRadius:7,pointBorderWidth:2}]},options:{animation:{duration:600,easing:'easeOutQuart'},responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'bottom',labels:{color:c.text}}},scales:{x:{type:'linear',min:0,max:maxQ,title:{display:true,text:'Количество, шт.',color:c.text},ticks:{color:c.text},grid:{color:c.grid}},y:{title:{display:true,text:'Рубли',color:c.text},ticks:{color:c.text},grid:{color:c.grid}}}}})}}
function money(v){return Number.isFinite(v)?Math.round(v).toLocaleString('ru-RU')+' ₽':'—'}
function calcTaxes(){const income=n('#napdIncome'),ind=n('#napdIndividuals'),companies=n('#napdCompanies'),emp=n('#napdEmployees'),napd=$('#napdResult');const shareTotal=ind+companies;let napdTax=0;if(emp>0){napd.innerHTML='НПД заблокирован: наличие сотрудников по 422-ФЗ';napd.className='result bad'}else if(income>2400000){napd.innerHTML='НПД заблокирован: лимит 2,4 млн ₽ превышен';napd.className='result bad'}else if(shareTotal<=0){napd.innerHTML='Укажите распределение дохода между физлицами и организациями';napd.className='result bad'}else{napdTax=ind*.04+companies*.06;napd.innerHTML=`Налог: <b>${money(napdTax)}</b> · эффективная ставка ${(napdTax/income*100).toFixed(2)}%`;napd.className='result'}const ui=n('#usnIncome'),ins=n('#usnInsurance'),ue=n('#usnEmployees'),gross=ui*.06,limit=ue>0?gross*.5:gross,deduction=Math.min(ins,limit),usn=Math.max(0,gross-deduction);$('#usnResult').innerHTML=`Налог: <b>${money(usn)}</b><br><small>Вычет ${money(deduction)} (лимит 50% при сотрудниках)</small>`;const u15=n('#usn15Income'),ex=n('#usn15Expenses'),minRate=n('#usn15Min')/100,base=Math.max(0,u15-ex),regular=base*.15,minTax=u15*minRate,usn15=Math.max(regular,minTax);$('#usn15Result').innerHTML=`Налог: <b>${money(usn15)}</b><br><small>${regular<minTax?'Применён минимальный налог':'Доходы минус расходы'}</small>`;$('#taxCompare').innerHTML=`<b>Сравнение:</b> НПД ${money(napdTax||0)} · УСН 6% ${money(usn)} · УСН 15% ${money(usn15)}`;const amount=n('#loanAmount'),rate=n('#loanRate')/1200,term=n('#loanTerm'),pay=rate?amount*rate/(1-Math.pow(1+rate,-term)):amount/Math.max(term,1),leaseCost=n('#leaseCost'),advance=leaseCost*n('#leaseAdvance')/100,leaseBase=leaseCost-advance,leaseTotal=leaseBase*(1+n('#leaseRate')/100),leasePay=leaseTotal/Math.max(n('#leaseTerm'),1);$('#loanResult').innerHTML=`Платёж: <b>${money(pay)}</b>/мес.<br><small>Переплата: ${money(pay*term-amount)}</small>`;$('#leaseResult').innerHTML=`Аванс: <b>${money(advance)}</b><br>Платёж: <b>${money(leasePay)}</b>/мес.<br><small>Итого выплат: ${money(advance+leaseTotal)}</small>`;$('#financeCompare').innerHTML=`<b>Сравнение финансирования:</b> кредит всего ${money(pay*term)} · лизинг всего ${money(advance+leaseTotal)}`}function calcEngineering(){const rho=n('#metal'),l=n('#metalLength')/1000,w=n('#metalWidth')/1000,h=n('#metalHeight')/1000;let v=$('#metalShape').value==='cylinder'?Math.PI*Math.pow(w/2,2)*l:l*w*h;$('#metalResult').textContent=`${(rho*v).toFixed(3)} кг`;const p=n('#volt')*n('#amp')*n('#cos')*(n('#phases')===3?Math.sqrt(3):1)/1000;$('#powerResult').textContent=`${p.toFixed(3)} кВт`}
function calcDepreciation(){const initial=n('#deprInitial'),residual=Math.min(n('#deprResidual'),initial),life=n('#deprLife'),base=Math.max(0,initial-residual),annual=life?base/life:0,monthly=annual/12,rate=life?100/life:0,afterYear=Math.max(residual,initial-annual);$('#deprResult').innerHTML=`Норма: <b>${rate.toFixed(2)}%</b> в год<br>Амортизация за год: <b>${money(annual)}</b><br>За месяц: <b>${money(monthly)}</b><br>Остаточная стоимость через 1 год: <b>${money(afterYear)}</b>`}
function calcCutting(){const diameter=n('#cuttingDiameter'),speed=n('#spindleSpeed'),value=Math.PI*diameter*speed/1000;let advice='Низкая скорость';if(value>=80&&value<=250)advice='Нормальная скорость для стали / чугуна';else if(value>250)advice='Высокая скорость';$('#cuttingResult').textContent=`${value.toFixed(1)} м/мин`;$('#cuttingAdvice').textContent=advice}
function calendarStamp(date,time){const y=date.getFullYear(),m=String(date.getMonth()+1).padStart(2,'0'),d=String(date.getDate()).padStart(2,'0');return `${y}${m}${d}T${time.replace(':','')}00`}
function calendarUtcStamp(date){const y=date.getUTCFullYear(),m=String(date.getUTCMonth()+1).padStart(2,'0'),d=String(date.getUTCDate()).padStart(2,'0'),h=String(date.getUTCHours()).padStart(2,'0'),min=String(date.getUTCMinutes()).padStart(2,'0'),s=String(date.getUTCSeconds()).padStart(2,'0');return `${y}${m}${d}T${h}${min}${s}Z`}
function icsText(value){return String(value||'').replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/\r?\n/g,'\\n')}
function exportScheduleCalendar(){const group=$('#groupSelect').value,dayIndex=selectedDay,now=new Date(),monday=new Date(now);monday.setHours(0,0,0,0);const offset=monday.getDay()===0?-6:1-monday.getDay();monday.setDate(monday.getDate()+offset);const date=new Date(monday);date.setDate(monday.getDate()+dayIndex);const lessons=(schedule[group]&&schedule[group][days[dayIndex]])||[],events=lessons.map((lesson,index)=>{if(!lesson[0]||lesson[0]==='—')return '';const period=periods[index%periods.length];return `BEGIN:VEVENT\r\nUID:upk-${date.getTime()}-${index}@upk-portal\r\nDTSTAMP:${calendarUtcStamp(new Date())}\r\nDTSTART;TZID=Europe/Moscow:${calendarStamp(date,period.start)}\r\nDTEND;TZID=Europe/Moscow:${calendarStamp(date,period.end)}\r\nSUMMARY:${icsText(lesson[0])}\r\nDESCRIPTION:${icsText(`Преподаватель: ${lesson[1]}`)}\r\nLOCATION:${icsText(lesson[2])}\r\nEND:VEVENT`}).filter(Boolean).join('\r\n');const content=`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//UPK Portal//Schedule//RU\r\nCALSCALE:GREGORIAN\r\nX-WR-TIMEZONE:Europe/Moscow\r\nX-WR-CALNAME:${icsText(`Расписание ${group}`)}\r\n${events}\r\nEND:VCALENDAR\r\n`;const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type:'text/calendar;charset=utf-8'}));link.download='upk-schedule.ics';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
function summary(){const profile=$('#profileSelect').value,price=n('#cvpPrice'),variable=n('#cvpVariable'),fixed=n('#cvpFixed'),quantity=n('#cvpQuantity'),margin=price-variable,bep=margin>0?fixed/margin:0,revenue=price*quantity,profit=margin*quantity-fixed,safety=quantity&&margin>0?(quantity-bep)/quantity*100:0,common=[['Группа',$('#groupSelect').value]],finance=[['Цена за единицу',money(price)],['Переменные затраты',money(variable)],['Постоянные затраты',money(fixed)],['Плановый объём',quantity+' шт.'],['Выручка',money(revenue)],['Прибыль / убыток',money(profit)],['Точка безубыточности',margin>0?Math.ceil(bep)+' шт.':'—'],['Запас финансовой прочности',margin>0?safety.toFixed(1)+'%':'—'],['Рекомендация по налогам',$('#taxCompare').textContent||'—'],['Нормативная база','422-ФЗ; п. 3.1 ст. 346.21 НК РФ'],['Кредит / лизинг',$('#financeCompare').textContent||'—'],['Амортизация ОС',$('#deprResult').textContent||'—']],tech=[['Материал',$('#metal').selectedOptions[0].text],['Форма заготовки',$('#metalShape').selectedOptions[0].text],['Длина / ширина / высота',`${$('#metalLength').value} / ${$('#metalWidth').value} / ${$('#metalHeight').value} мм`],['Плотность',`${$('#metal').value} кг/м³`],['Масса',$('#metalResult').textContent],['Напряжение / ток',`${$('#volt').value} В / ${$('#amp').value} А`],['cos φ',$('#cos').value],['Фазы',$('#phases').value],['Потребляемая мощность',$('#powerResult').textContent]];const block=(title,rows)=>`<div class="summary-block"><h2>${title}</h2>${rows.map(r=>`<div class="summary-row"><span>${r[0]}</span><span>${r[1]||'—'}</span></div>`).join('')}</div>`;let html='<div class="print-title"><b>УПК</b><span>'+({economy:'Финансово-экономический паспорт проекта',technical:'Ведомость технологических расчётов',admin:'Сводный отчёт по модулям'}[profile])+'</span><span>'+new Date().toLocaleDateString('ru-RU')+'</span></div>'+block('Общие параметры',common);if(profile==='economy')html+=block('Финансово-экономический паспорт проекта',finance);else if(profile==='technical')html+=block('Ведомость технологических расчётов',tech);else html+=block('Финансово-экономический блок',finance)+block('Технический блок',tech);$('#summaryContent').innerHTML=html+'<p class="muted">Аналитическое резюме: '+(profile==='technical'?'расчётные параметры заготовки и электросети подготовлены для технологического анализа.':'финансовые показатели и режим налогообложения сопоставлены для принятия управленческого решения.')+'</p><div class="signatures">Выполнил студент группы: ____________________<br><br>Проверил преподаватель: ____________________</div>';}
$$('.module-tab').forEach(b=>b.onclick=()=>{$$('.module-tab').forEach(x=>x.classList.remove('active'));$$('.module-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
function allCalc(){calcEconomy();calcTaxes();calcEngineering();calcDepreciation();calcCutting();summary()}
const storageKey='upkStudentPortal';
function saveState(e){if(e&&e.target.id)try{localStorage.setItem(storageKey+':'+e.target.id,e.target.value)}catch(_){}}
function restoreState(){const profile=localStorage.getItem(storageKey+':profileSelect')||'economy';$('#profileSelect').value=profile;$('#profileSelectMobile').value=profile;$$('input,select').forEach(e=>{const v=localStorage.getItem(storageKey+':'+e.id);if(v!==null&&!['profileSelect','profileSelectMobile'].includes(e.id))e.value=v});applyProfile(profile)}
function applyProfile(profile){$$('.nav-item[data-profile]').forEach(b=>b.hidden=profile!=='admin'&&b.dataset.profile!==profile);const select=$('#groupSelect'),options=[...select.options];options.forEach(o=>o.hidden=profile!=='admin'&&o.dataset.profile!==profile);const available=options.find(o=>!o.hidden);if(select.selectedOptions[0]&&select.selectedOptions[0].hidden&&available)select.value=available.value;renderSchedule();summary();if($('#editorGroup'))editorRows()}
function csvData(){const profile=$('#profileSelect').value,rows=[['Раздел','Показатель','Значение'],['Параметры','Профиль',$('#profileSelect').selectedOptions[0].text],['Параметры','Группа',$('#groupSelect').value]];if(profile!=='technical')rows.push(['Финансы','Выручка',$('#mRevenue').textContent],['Финансы','Прибыль / убыток',$('#mProfit').textContent],['Финансы','Точка безубыточности',$('#mBep').textContent],['Финансы','Запас финансовой прочности',$('#mSafety').textContent],['Финансы','Налоговая рекомендация',$('#taxCompare').textContent],['Финансы','Кредит / лизинг',$('#financeCompare').textContent]);if(profile!=='economy')rows.push(['Технология','Материал',$('#metal').selectedOptions[0].text],['Технология','Плотность',$('#metal').value+' кг/м³'],['Технология','Масса',$('#metalResult').textContent],['Технология','Напряжение / ток',$('#volt').value+' В / '+$('#amp').value+' А'],['Технология','Мощность',$('#powerResult').textContent]);return '﻿'+rows.map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(';')).join('\r\n')}
function downloadCsv(){const a=document.createElement('a');a.href='data:text/csv;charset=utf-8,'+encodeURIComponent(csvData());a.download='upk-summary.csv';a.click()}
function copySummary(){const text=$('#summaryContent').innerText;const done=()=>{const b=$('#copyBtn');b.textContent='Скопировано';setTimeout(()=>b.textContent='Копировать для Word',1200)};if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(text).then(done).catch(()=>{fallbackCopy(text);done()});else{fallbackCopy(text);done()}}
function fallbackCopy(text){const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}
function openQr(){const url=location.href;$('#qrLink').textContent=url;$('#qrCode').innerHTML='';if(window.QRCode)new QRCode($('#qrCode'),{text:url,width:220,height:220,colorDark:'#111827',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});else $('#qrCode').textContent='QR-библиотека ещё загружается. Повторите открытие окна.';$('#qrModal').hidden=false}
function closeQr(){$('#qrModal').hidden=true}
function importSchedule(){const raw=$('#scheduleImport').value.trim();if(!raw)return;try{const text=raw.replace(/^\s*const\s+(?:schedule|baseSchedule)\s*=\s*/,'').replace(/;\s*$/,'');const imported=JSON.parse(text);if(!imported||typeof imported!=='object')throw new Error('Неверный объект');schedule=JSON.parse(JSON.stringify(baseSchedule));Object.entries(imported).forEach(([group,groupDays])=>{schedule[group]||(schedule[group]={});Object.entries(groupDays||{}).forEach(([day,lessons])=>{if(days.includes(day))schedule[group][day]=cleanLessons(lessons)});});saveCustomSchedule();refreshGroupOptions();renderSchedule();editorRows();$('#editorStatus').textContent='Расписание импортировано и сохранено на этом компьютере.'}catch(error){$('#editorStatus').textContent='Не удалось импортировать: вставьте JSON или корректный экспортированный код.'}}
function registerServiceWorker(){if(!('serviceWorker' in navigator)||location.protocol==='file:')return;let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(!refreshing){refreshing=true;window.location.reload()}});window.addEventListener('load',()=>{navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(registration=>{const update=()=>registration.update().catch(error=>console.error('Не удалось проверить обновление Service Worker:',error));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')update()});setInterval(update,5*60*1000);update()}).catch(error=>console.error('Не удалось зарегистрировать Service Worker:',error))})}
function syncTitleGroup(){const select=$('#titleGroup');if(!select)return;select.innerHTML=[...$('#groupSelect').options].map(o=>`<option value="${escapeHtml(o.value)}">${escapeHtml(o.textContent)}</option>`).join('');select.value=$('#groupSelect').value}
function printTitle(){const type=$('#titleType').value,subject=$('#titleSubject').value||'________________',topic=$('#titleTopic').value||'________________',teacher=$('#titleTeacher').value||'________________',student=$('#titleStudent').value.trim(),group=$('#titleGroup').value,year=new Date().getFullYear(),studentLine=student?escapeHtml(student):'____________________________';const win=window.open('','_blank','width=900,height=700');if(!win){alert('Разрешите всплывающие окна для печати титульного листа.');return}win.document.write(`<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Титульный лист</title><style>@page{size:A4;margin:20mm}body{font-family:"Times New Roman",serif;font-size:14pt;color:#000}.center{text-align:center}.topic{margin-top:55mm;text-align:center;font-size:16pt;font-weight:bold}.details{margin-top:35mm;margin-left:52%;line-height:1.7}.footer{position:fixed;bottom:12mm;left:0;right:0;text-align:center}</style></head><body><div class="center">МИНИСТЕРСТВО ОБРАЗОВАНИЯ ТУЛЬСКОЙ ОБЛАСТИ<br>ГПОУ ТО «УЗЛОВСКИЙ ПОЛИТЕХНИЧЕСКИЙ КОЛЛЕДЖ»</div><div class="topic">${escapeHtml(type)}<br>по дисциплине «${escapeHtml(subject)}»<br>на тему: «${escapeHtml(topic)}»</div><div class="details">Выполнил студент группы ${escapeHtml(group)}<br>${studentLine}<br><br>Проверил преподаватель<br>${escapeHtml(teacher)}<br>____________________________</div><div class="footer">Узловая<br>${year}</div><script>window.onload=()=>{window.print();window.onafterprint=()=>window.close()}<\/script></body></html>`);win.document.close()}
function calcGrades(){const excellent=Math.max(0,n('#gradeExcellent')),good=Math.max(0,n('#gradeGood')),satisfactory=Math.max(0,n('#gradeSatisfactory')),total=excellent+good+satisfactory,gpa=total?(excellent*5+good*4+satisfactory*3)/total:0,share=total?excellent/total*100:0;let verdict='Введите количество оценок.';if(total&&satisfactory>0)verdict='Обычный диплом (есть удовлетворительные оценки)';else if(total&&share>=75)verdict='Претендует на диплом с отличием (красный диплом) ★';else if(total){const needed=Math.max(0,Math.ceil((.75*total-excellent)/.25));verdict=`Для красного диплома не хватает ${needed} пятёрок`};$('#gradeResult').innerHTML=`Средний балл: <b>${gpa.toFixed(2)}</b><br>Доля пятёрок: <b>${share.toFixed(1)}%</b><br><span>${verdict}</span>`}
function loadDeadlines(){let list=[];try{list=JSON.parse(localStorage.getItem('upk_deadlines')||'[]')}catch(_){list=[]}const today=new Date();today.setHours(0,0,0,0);$('#deadlineList').innerHTML=list.sort((a,b)=>a.date.localeCompare(b.date)).map(item=>{const date=new Date(`${item.date}T00:00:00`),diff=Math.round((date-today)/86400000),label=diff<0?'Срок прошел':diff===0?'Сегодня сдача':`Осталось ${diff} дн.`,subject=item.subject?`<span class="deadline-subject">${escapeHtml(item.subject)}</span>`:'';return `<div class="deadline-item ${item.done?'done':''}"><div><strong>${escapeHtml(item.title)}</strong><small>${date.toLocaleDateString('ru-RU')}</small>${subject}</div><span class="deadline-badge ${diff<0?'overdue':''}">${label}</span><div class="deadline-actions"><button class="secondary deadline-toggle" data-id="${item.id}" type="button">${item.done?'Вернуть':'Готово'}</button><button class="secondary deadline-delete" data-id="${item.id}" type="button">Удалить</button></div></div>`}).join('')||'<p class="muted">Дедлайнов пока нет.</p>';$$('.deadline-toggle').forEach(b=>b.onclick=()=>updateDeadline(b.dataset.id));$$('.deadline-delete').forEach(b=>b.onclick=()=>deleteDeadline(b.dataset.id))}
function saveDeadlines(list){localStorage.setItem('upk_deadlines',JSON.stringify(list));loadDeadlines()}
function updateDeadline(id){const list=JSON.parse(localStorage.getItem('upk_deadlines')||'[]');const item=list.find(x=>x.id===id);if(item)item.done=!item.done;saveDeadlines(list)}
function deleteDeadline(id){saveDeadlines(JSON.parse(localStorage.getItem('upk_deadlines')||'[]').filter(x=>x.id!==id))}
function clearCompletedDeadlines(){saveDeadlines(JSON.parse(localStorage.getItem('upk_deadlines')||'[]').filter(item=>!item.done))}
function addDeadline(){const title=$('#deadlineTitle').value.trim(),subject=$('#deadlineSubject').value.trim(),date=$('#deadlineDate').value;if(!title||!date)return;const list=JSON.parse(localStorage.getItem('upk_deadlines')||'[]');list.push({id:Date.now().toString(),title,subject,date,done:false});saveDeadlines(list);$('#deadlineTitle').value='';$('#deadlineSubject').value='';$('#deadlineDate').value=''}
function initInstallPrompt(){window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;$('#installPwaBtn').hidden=false});window.addEventListener('appinstalled',()=>{deferredPrompt=null;$('#installPwaBtn').hidden=true});$('#installPwaBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installPwaBtn').hidden=true}}
function closeSidebar(){ $('#sidebar').classList.remove('open');$('#sidebarOverlay').classList.remove('visible'); }
let editorUnlocked=false;
$$('.nav-item').forEach(b=>b.onclick=()=>{if(b.dataset.section==='schedule-editor'&&!editorUnlocked){const expected=localStorage.getItem('upk_editor_pin')||'1234';if(prompt('Введите PIN-код редактора расписания:')!==expected){alert('Неверный PIN-код.');return}editorUnlocked=true}$$('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.section').forEach(s=>s.classList.toggle('active',s.id===b.dataset.section));closeSidebar();window.scrollTo({top:0,behavior:'smooth'});if(b.dataset.section==='summary')summary()});
$('#groupSelect').onchange=()=>{saveState({target:$('#groupSelect')});syncTitleGroup();renderSchedule();summary()};$$('#profileSelect,#profileSelectMobile').forEach(e=>e.onchange=event=>{$('#profileSelect').value=event.target.value;$('#profileSelectMobile').value=event.target.value;localStorage.setItem(storageKey+':profileSelect',event.target.value);applyProfile(event.target.value)});$('#roomSearch').oninput=e=>{saveState(e);renderRooms()};$('#buildingFilter').onchange=e=>{saveState(e);renderRooms()};$$('input,select').forEach(e=>{e.addEventListener('input',e=>{saveState(e);allCalc()});e.addEventListener('change',e=>{saveState(e);allCalc()})});$('#printBtn').onclick=()=>window.print();$('#csvBtn').onclick=downloadCsv;$('#copyBtn').onclick=copySummary;$('#resetBtn').onclick=()=>{Object.keys(localStorage).filter(k=>k.startsWith(storageKey+':')).forEach(k=>localStorage.removeItem(k));location.reload()};$('#menuBtn').onclick=()=>{$('#sidebar').classList.toggle('open');$('#sidebarOverlay').classList.toggle('visible',$('#sidebar').classList.contains('open'))};$('#sidebarOverlay').onclick=closeSidebar;$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem(storageKey+':theme',document.body.classList.contains('dark')?'dark':'light');syncChartTheme()};$('#qrBtn').onclick=openQr;$('#closeQrBtn').onclick=closeQr;$('#qrModal').onclick=e=>{if(e.target.id==='qrModal')closeQr()};$('#copyLinkBtn').onclick=()=>{const done=()=>{$('#copyLinkBtn').textContent='Ссылка скопирована';setTimeout(()=>$('#copyLinkBtn').textContent='Скопировать ссылку',1500)};if(navigator.clipboard)navigator.clipboard.writeText(location.href).then(done).catch(()=>{fallbackCopy(location.href);done()});else{fallbackCopy(location.href);done()}};$('#editorGroup').onchange=editorRows;$('#editorDay').onchange=editorRows;$('#addGroupBtn').onclick=addEditorGroup;$('#saveScheduleBtn').onclick=saveEditor;$('#exportScheduleBtn').onclick=exportScheduleCode;$('#resetScheduleBtn').onclick=resetCustomSchedule;$('#importScheduleBtn').onclick=importSchedule;$('#changePinBtn').onclick=()=>{const oldPin=localStorage.getItem('upk_editor_pin')||'1234';if(prompt('Текущий PIN-код:')!==oldPin)return;const next=prompt('Новый PIN-код:');if(next&&/^\d{4,}$/.test(next)){localStorage.setItem('upk_editor_pin',next);$('#editorStatus').textContent='PIN-код изменён.'}else alert('PIN должен содержать минимум 4 цифры.')};$('#copyScheduleCodeBtn').onclick=()=>{const copy=navigator.clipboard?.writeText($('#scheduleCode').value);if(copy)copy.then(()=>$('#editorStatus').textContent='Код расписания скопирован в буфер.').catch(()=>{fallbackCopy($('#scheduleCode').value);$('#editorStatus').textContent='Код расписания скопирован в буфер.'});else{fallbackCopy($('#scheduleCode').value);$('#editorStatus').textContent='Код расписания скопирован в буфер.'}};
$('#calendarExportBtn').onclick=exportScheduleCalendar;$('#tomorrowBtn').onclick=selectTomorrow;$('#printTitleBtn').onclick=printTitle;$('#gradeExcellent').oninput=calcGrades;$('#gradeGood').oninput=calcGrades;$('#gradeSatisfactory').oninput=calcGrades;$('#addDeadlineBtn').onclick=addDeadline;$('#clearCompletedBtn').onclick=clearCompletedDeadlines;loadCustomSchedule();restoreState();initEditor();initMethodology();initInstallPrompt();syncTitleGroup();calcGrades();loadDeadlines();if(localStorage.getItem(storageKey+':theme')==='dark'){$('#themeBtn').click()}clock();setInterval(clock,1000);renderSchedule();renderRooms();allCalc();registerServiceWorker();
